#include "Renderer2D.h"
#include "Context.h"
#include "FormatUtils.h"

#include <Lumina/Core/Device.h>
#include <Lumina/Core/Profiler.h>
#include "EmbeddedFont.h"

#include <Lumina/Core/Log.h>

#include <glm/gtc/matrix_transform.hpp>

// Embedded shader bytecode (generated by compile-shaders script)
#include "shaders/quad_vs.h"
#include "shaders/quad_ps.h"
#include "shaders/line_vs.h"
#include "shaders/line_ps.h"
#include "shaders/circle_vs.h"
#include "shaders/circle_ps.h"
#include "shaders/text_vs.h"
#include "shaders/text_ps.h"
#include "shaders/triangle_vs.h"
#include "shaders/triangle_ps.h"
#include "shaders/pixel_vs.h"
#include "shaders/pixel_ps.h"
#include "shaders/grid_vs.h"
#include "shaders/grid_ps.h"
#include "shaders/point_light_vs.h"
#include "shaders/point_light_ps.h"
#include "shaders/composite_vs.h"
#include "shaders/composite_ps.h"

namespace
{
    // Helper to get correct bytecode for current backend
    struct ShaderBytecode
    {
        const void* Data;
        size_t Size;
    };

    // Quad shaders
    ShaderBytecode GetQuadVS(Lumina::Core::GraphicsAPI api)
    {
        if (api == Lumina::Core::GraphicsAPI::D3D12)
            return { g_quad_vs_dxil, sizeof(g_quad_vs_dxil) };
        else
            return { g_quad_vs_spirv, sizeof(g_quad_vs_spirv) };
    }

    ShaderBytecode GetQuadPS(Lumina::Core::GraphicsAPI api)
    {
        if (api == Lumina::Core::GraphicsAPI::D3D12)
            return { g_quad_ps_dxil, sizeof(g_quad_ps_dxil) };
        else
            return { g_quad_ps_spirv, sizeof(g_quad_ps_spirv) };
    }

    // Line shaders
    ShaderBytecode GetLineVS(Lumina::Core::GraphicsAPI api)
    {
        if (api == Lumina::Core::GraphicsAPI::D3D12)
            return { g_line_vs_dxil, sizeof(g_line_vs_dxil) };
        else
            return { g_line_vs_spirv, sizeof(g_line_vs_spirv) };
    }

    ShaderBytecode GetLinePS(Lumina::Core::GraphicsAPI api)
    {
        if (api == Lumina::Core::GraphicsAPI::D3D12)
            return { g_line_ps_dxil, sizeof(g_line_ps_dxil) };
        else
            return { g_line_ps_spirv, sizeof(g_line_ps_spirv) };
    }

    // Circle shaders
    ShaderBytecode GetCircleVS(Lumina::Core::GraphicsAPI api)
    {
        if (api == Lumina::Core::GraphicsAPI::D3D12)
            return { g_circle_vs_dxil, sizeof(g_circle_vs_dxil) };
        else
            return { g_circle_vs_spirv, sizeof(g_circle_vs_spirv) };
    }

    ShaderBytecode GetCirclePS(Lumina::Core::GraphicsAPI api)
    {
        if (api == Lumina::Core::GraphicsAPI::D3D12)
            return { g_circle_ps_dxil, sizeof(g_circle_ps_dxil) };
        else
            return { g_circle_ps_spirv, sizeof(g_circle_ps_spirv) };
    }

    // Text shaders
    ShaderBytecode GetTextVS(Lumina::Core::GraphicsAPI api)
    {
        if (api == Lumina::Core::GraphicsAPI::D3D12)
            return { g_text_vs_dxil, sizeof(g_text_vs_dxil) };
        else
            return { g_text_vs_spirv, sizeof(g_text_vs_spirv) };
    }

    ShaderBytecode GetTextPS(Lumina::Core::GraphicsAPI api)
    {
        if (api == Lumina::Core::GraphicsAPI::D3D12)
            return { g_text_ps_dxil, sizeof(g_text_ps_dxil) };
        else
            return { g_text_ps_spirv, sizeof(g_text_ps_spirv) };
    }

    // Triangle shaders
    ShaderBytecode GetTriangleVS(Lumina::Core::GraphicsAPI api)
    {
        if (api == Lumina::Core::GraphicsAPI::D3D12)
            return { g_triangle_vs_dxil, sizeof(g_triangle_vs_dxil) };
        else
            return { g_triangle_vs_spirv, sizeof(g_triangle_vs_spirv) };
    }

    ShaderBytecode GetTrianglePS(Lumina::Core::GraphicsAPI api)
    {
        if (api == Lumina::Core::GraphicsAPI::D3D12)
            return { g_triangle_ps_dxil, sizeof(g_triangle_ps_dxil) };
        else
            return { g_triangle_ps_spirv, sizeof(g_triangle_ps_spirv) };
    }

    // Pixel shaders
    ShaderBytecode GetPixelVS(Lumina::Core::GraphicsAPI api)
    {
        if (api == Lumina::Core::GraphicsAPI::D3D12)
            return { g_pixel_vs_dxil, sizeof(g_pixel_vs_dxil) };
        else
            return { g_pixel_vs_spirv, sizeof(g_pixel_vs_spirv) };
    }

    ShaderBytecode GetPixelPS(Lumina::Core::GraphicsAPI api)
    {
        if (api == Lumina::Core::GraphicsAPI::D3D12)
            return { g_pixel_ps_dxil, sizeof(g_pixel_ps_dxil) };
        else
            return { g_pixel_ps_spirv, sizeof(g_pixel_ps_spirv) };
    }

    // Grid shaders
    ShaderBytecode GetGridVS(Lumina::Core::GraphicsAPI api)
    {
        if (api == Lumina::Core::GraphicsAPI::D3D12)
            return { g_grid_vs_dxil, sizeof(g_grid_vs_dxil) };
        else
            return { g_grid_vs_spirv, sizeof(g_grid_vs_spirv) };
    }

    ShaderBytecode GetGridPS(Lumina::Core::GraphicsAPI api)
    {
        if (api == Lumina::Core::GraphicsAPI::D3D12)
            return { g_grid_ps_dxil, sizeof(g_grid_ps_dxil) };
        else
            return { g_grid_ps_spirv, sizeof(g_grid_ps_spirv) };
    }

    // Point light shaders
    ShaderBytecode GetPointLightVS(Lumina::Core::GraphicsAPI api)
    {
        if (api == Lumina::Core::GraphicsAPI::D3D12)
            return { g_point_light_vs_dxil, sizeof(g_point_light_vs_dxil) };
        else
            return { g_point_light_vs_spirv, sizeof(g_point_light_vs_spirv) };
    }

    ShaderBytecode GetPointLightPS(Lumina::Core::GraphicsAPI api)
    {
        if (api == Lumina::Core::GraphicsAPI::D3D12)
            return { g_point_light_ps_dxil, sizeof(g_point_light_ps_dxil) };
        else
            return { g_point_light_ps_spirv, sizeof(g_point_light_ps_spirv) };
    }

    // Composite shaders
    ShaderBytecode GetCompositeVS(Lumina::Core::GraphicsAPI api)
    {
        if (api == Lumina::Core::GraphicsAPI::D3D12)
            return { g_composite_vs_dxil, sizeof(g_composite_vs_dxil) };
        else
            return { g_composite_vs_spirv, sizeof(g_composite_vs_spirv) };
    }

    ShaderBytecode GetCompositePS(Lumina::Core::GraphicsAPI api)
    {
        if (api == Lumina::Core::GraphicsAPI::D3D12)
            return { g_composite_ps_dxil, sizeof(g_composite_ps_dxil) };
        else
            return { g_composite_ps_spirv, sizeof(g_composite_ps_spirv) };
    }
}

namespace Lumina
{
    Renderer2D::Renderer2D(Core::Device& dev)
        : m_Device(dev)
    {
    }

    Renderer2D::~Renderer2D()
    {
        Shutdown();
    }

    bool Renderer2D::Init(const Renderer2DConfig& config)
    {
        if (m_Initialized)
            return true;

        m_Config = config;

        // Create rendering context
        m_Context = MakeScope<Context>(m_Device);
        if (!m_Context)
        {
            LUMINA_LOG_ERROR("Failed to create rendering context");
            return false;
        }

        // Create pipeline cache to keep pipelines alive across flushes
        m_PipelineCache = MakeScope<PipelineCache>(m_Device);

        // Reserve point lights storage (layers are created on-demand)
        m_PointLights.reserve(config.MaxPointLights);

        // ========================================================================
        // Create shared resources
        // ========================================================================

        // Default sampler (linear)
        m_DefaultSampler = Sampler::Create(m_Device, Samplers::LinearClamp());
        if (!m_DefaultSampler)
        {
            LUMINA_LOG_ERROR("Failed to create default sampler");
            return false;
        }

        // Point sampler (for pixel art)
        m_PointSampler = Sampler::Create(m_Device, Samplers::PointClamp());
        if (!m_PointSampler)
        {
            LUMINA_LOG_ERROR("Failed to create point sampler");
            return false;
        }

        // Set current sampler to default (linear)
        m_CurrentSampler = m_DefaultSampler;
        m_FilterMode = FilterMode::Linear;

        // 1x1 white texture
        uint32_t whitePixel = 0xFFFFFFFF;
        m_WhiteTexture = Texture::Create(m_Device, 1, 1, Format::RGBA8Unorm, &whitePixel);
        if (!m_WhiteTexture)
        {
            LUMINA_LOG_ERROR("Failed to create white texture");
            return false;
        }

        // Camera constant buffer
        m_CameraBuffer = UniformBuffer::Create<CameraData>(m_Device);
        if (!m_CameraBuffer)
        {
            LUMINA_LOG_ERROR("Failed to create camera buffer");
            return false;
        }

        // Create default font from embedded TTF
        m_DefaultFont = FontAtlas::Create(m_Device, embedded_font_data, embedded_font_size, 16.0f);
        if (!m_DefaultFont)
        {
            LUMINA_LOG_ERROR("Failed to create default font atlas");
            return false;
        }

        // ========================================================================
        // Create quad resources
        // ========================================================================

        // Quad vertex buffer
        size_t quadVbSize = config.MaxQuads * VerticesPerQuad * sizeof(QuadVertex);
        m_QuadVertexBuffer = VertexBuffer::Create(m_Device, nullptr, quadVbSize, sizeof(QuadVertex), BufferUsage::Dynamic);
        if (!m_QuadVertexBuffer)
        {
            LUMINA_LOG_ERROR("Failed to create quad vertex buffer");
            return false;
        }

        // Quad index buffer (static - precomputed)
        std::vector<uint32_t> quadIndices(config.MaxQuads * IndicesPerQuad);
        uint32_t offset = 0;
        for (uint32_t i = 0; i < config.MaxQuads; i++)
        {
            quadIndices[i * 6 + 0] = offset + 0;
            quadIndices[i * 6 + 1] = offset + 1;
            quadIndices[i * 6 + 2] = offset + 2;
            quadIndices[i * 6 + 3] = offset + 2;
            quadIndices[i * 6 + 4] = offset + 3;
            quadIndices[i * 6 + 5] = offset + 0;
            offset += 4;
        }
        m_QuadIndexBuffer = IndexBuffer::Create(m_Device, quadIndices.data(), quadIndices.size(), sizeof(uint32_t));
        if (!m_QuadIndexBuffer)
        {
            LUMINA_LOG_ERROR("Failed to create quad index buffer");
            return false;
        }

        // Quad shader
        {
            auto vs = GetQuadVS(m_Device.GetAPI());
            auto ps = GetQuadPS(m_Device.GetAPI());

            ShaderDesc desc;
            desc.VertexBlob = vs.Data;
            desc.VertexSize = vs.Size;
            desc.PixelBlob = ps.Data;
            desc.PixelSize = ps.Size;
            desc.VertexEntry = "VSMain";
            desc.PixelEntry = "PSMain";
            desc.DebugName = "Renderer2D Quad";

            m_QuadShader = Shader::Create(m_Device, desc);
            if (!m_QuadShader)
            {
                LUMINA_LOG_ERROR("Failed to create quad shader");
                return false;
            }
        }

        // Quad input layout
        InputLayoutDesc quadLayoutDesc;
        quadLayoutDesc.Add("POSITION", Format::RGBA32Float, VertexSemantic::Position)
                      .Add("COLOR", Format::RGBA32Float, VertexSemantic::Color)
                      .Add("TEXCOORD", Format::RG32Float, VertexSemantic::Texcoord)
                      .Add("TEXINDEX", Format::R32Float, VertexSemantic::Custom)
                      .Add("ZINDEX", Format::R32Float, VertexSemantic::Custom);

        m_QuadInputLayout = InputLayout::Create(m_Device, quadLayoutDesc, m_QuadShader);
        if (!m_QuadInputLayout)
        {
            LUMINA_LOG_ERROR("Failed to create quad input layout");
            return false;
        }

        // Quad binding layout (constant buffer + texture array + sampler)
        BindingLayoutDesc quadBindingDesc;
        quadBindingDesc.AddConstantBuffer(0);     // Camera view-projection
        quadBindingDesc.AddTextureArray(0, 32);   // Up to 32 textures per batch
        quadBindingDesc.AddSampler(0);

        m_QuadBindingLayout = BindingLayout::Create(m_Device, quadBindingDesc);
        if (!m_QuadBindingLayout)
        {
            LUMINA_LOG_ERROR("Failed to create quad binding layout");
            return false;
        }

        // ========================================================================
        // Create circle resources
        // ========================================================================

        size_t circleVbSize = config.MaxCircles * VerticesPerQuad * sizeof(CircleVertex);
        m_CircleVertexBuffer = VertexBuffer::Create(m_Device, nullptr, circleVbSize, sizeof(CircleVertex), BufferUsage::Dynamic);
        if (!m_CircleVertexBuffer)
        {
            LUMINA_LOG_ERROR("Failed to create circle vertex buffer");
            return false;
        }

        // Reuse quad index buffer for circles
        m_CircleIndexBuffer = m_QuadIndexBuffer;

        // Circle shader
        {
            auto vs = GetCircleVS(m_Device.GetAPI());
            auto ps = GetCirclePS(m_Device.GetAPI());

            ShaderDesc desc;
            desc.VertexBlob = vs.Data;
            desc.VertexSize = vs.Size;
            desc.PixelBlob = ps.Data;
            desc.PixelSize = ps.Size;
            desc.VertexEntry = "VSMain";
            desc.PixelEntry = "PSMain";
            desc.DebugName = "Renderer2D Circle";

            m_CircleShader = Shader::Create(m_Device, desc);
            if (!m_CircleShader)
            {
                LUMINA_LOG_ERROR("Failed to create circle shader");
                return false;
            }
        }

        // Circle input layout
        InputLayoutDesc circleLayoutDesc;
        circleLayoutDesc.Add("POSITION", Format::RGBA32Float, VertexSemantic::Position)    // world_position
                        .Add("LOCALPOS", Format::RGBA32Float, VertexSemantic::Custom)      // local_position
                        .Add("COLOR", Format::RGBA32Float, VertexSemantic::Color)
                        .Add("TEXCOORD", Format::RG32Float, VertexSemantic::Texcoord)
                        .Add("TEXINDEX", Format::R32Float, VertexSemantic::Custom)
                        .Add("THICKNESS", Format::R32Float, VertexSemantic::Custom)
                        .Add("FADE", Format::R32Float, VertexSemantic::Custom)
                        .Add("ZINDEX", Format::R32Float, VertexSemantic::Custom);

        m_CircleInputLayout = InputLayout::Create(m_Device, circleLayoutDesc, m_CircleShader);
        if (!m_CircleInputLayout)
        {
            LUMINA_LOG_ERROR("Failed to create circle input layout");
            return false;
        }

        // Circle binding layout (same as quad)
        m_CircleBindingLayout = m_QuadBindingLayout;

        // ========================================================================
        // Create line resources
        // ========================================================================

        size_t lineVbSize = config.MaxLines * 2 * sizeof(LineVertex);
        m_LineVertexBuffer = VertexBuffer::Create(m_Device, nullptr, lineVbSize, sizeof(LineVertex), BufferUsage::Dynamic);
        if (!m_LineVertexBuffer)
        {
            LUMINA_LOG_ERROR("Failed to create line vertex buffer");
            return false;
        }

        // Line shader
        {
            auto vs = GetLineVS(m_Device.GetAPI());
            auto ps = GetLinePS(m_Device.GetAPI());

            ShaderDesc desc;
            desc.VertexBlob = vs.Data;
            desc.VertexSize = vs.Size;
            desc.PixelBlob = ps.Data;
            desc.PixelSize = ps.Size;
            desc.VertexEntry = "VSMain";
            desc.PixelEntry = "PSMain";
            desc.DebugName = "Renderer2D Line";

            m_LineShader = Shader::Create(m_Device, desc);
            if (!m_LineShader)
            {
                LUMINA_LOG_ERROR("Failed to create line shader");
                return false;
            }
        }

        // Line input layout
        InputLayoutDesc lineLayoutDesc;
        lineLayoutDesc.Add("POSITION", Format::RGBA32Float, VertexSemantic::Position)
                      .Add("COLOR", Format::RGBA32Float, VertexSemantic::Color);

        m_LineInputLayout = InputLayout::Create(m_Device, lineLayoutDesc, m_LineShader);
        if (!m_LineInputLayout)
        {
            LUMINA_LOG_ERROR("Failed to create line input layout");
            return false;
        }

        // Line binding layout (just camera constant buffer)
        BindingLayoutDesc lineBindingDesc;
        lineBindingDesc.AddConstantBuffer(0);

        m_LineBindingLayout = BindingLayout::Create(m_Device, lineBindingDesc);
        if (!m_LineBindingLayout)
        {
            LUMINA_LOG_ERROR("Failed to create line binding layout");
            return false;
        }

        // ========================================================================
        // Create text resources
        // ========================================================================

        size_t textVbSize = config.MaxTextChars * VerticesPerQuad * sizeof(TextVertex);
        m_TextVertexBuffer = VertexBuffer::Create(m_Device, nullptr, textVbSize, sizeof(TextVertex), BufferUsage::Dynamic);
        if (!m_TextVertexBuffer)
        {
            LUMINA_LOG_ERROR("Failed to create text vertex buffer");
            return false;
        }

        // Reuse quad index buffer for text
        m_TextIndexBuffer = m_QuadIndexBuffer;

        // Text shader
        {
            auto vs = GetTextVS(m_Device.GetAPI());
            auto ps = GetTextPS(m_Device.GetAPI());

            ShaderDesc desc;
            desc.VertexBlob = vs.Data;
            desc.VertexSize = vs.Size;
            desc.PixelBlob = ps.Data;
            desc.PixelSize = ps.Size;
            desc.VertexEntry = "VSMain";
            desc.PixelEntry = "PSMain";
            desc.DebugName = "Renderer2D Text";

            m_TextShader = Shader::Create(m_Device, desc);
            if (!m_TextShader)
            {
                LUMINA_LOG_ERROR("Failed to create text shader");
                return false;
            }
        }

        // Text input layout (same structure as quad)
        m_TextInputLayout = m_QuadInputLayout;

        // Text binding layout (same as quad)
        m_TextBindingLayout = m_QuadBindingLayout;

        // ========================================================================
        // Create triangle resources
        // ========================================================================

        size_t triangleVbSize = config.MaxTriangles * 3 * sizeof(TriangleVertex);
        m_TriangleVertexBuffer = VertexBuffer::Create(m_Device, nullptr, triangleVbSize, sizeof(TriangleVertex), BufferUsage::Dynamic);
        if (!m_TriangleVertexBuffer)
        {
            LUMINA_LOG_ERROR("Failed to create triangle vertex buffer");
            return false;
        }

        // Triangle shader
        {
            auto vs = GetTriangleVS(m_Device.GetAPI());
            auto ps = GetTrianglePS(m_Device.GetAPI());

            ShaderDesc desc;
            desc.VertexBlob = vs.Data;
            desc.VertexSize = vs.Size;
            desc.PixelBlob = ps.Data;
            desc.PixelSize = ps.Size;
            desc.VertexEntry = "VSMain";
            desc.PixelEntry = "PSMain";
            desc.DebugName = "Renderer2D Triangle";

            m_TriangleShader = Shader::Create(m_Device, desc);
            if (!m_TriangleShader)
            {
                LUMINA_LOG_ERROR("Failed to create triangle shader");
                return false;
            }
        }

        // Triangle input layout (same structure as quad)
        m_TriangleInputLayout = m_QuadInputLayout;

        // Triangle binding layout (same as quad)
        m_TriangleBindingLayout = m_QuadBindingLayout;

        // ========================================================================
        // Create pixel resources
        // ========================================================================

        size_t pixelVbSize = config.MaxPixels * sizeof(PixelVertex);
        m_PixelVertexBuffer = VertexBuffer::Create(m_Device, nullptr, pixelVbSize, sizeof(PixelVertex), BufferUsage::Dynamic);
        if (!m_PixelVertexBuffer)
        {
            LUMINA_LOG_ERROR("Failed to create pixel vertex buffer");
            return false;
        }

        // Pixel shader
        {
            auto vs = GetPixelVS(m_Device.GetAPI());
            auto ps = GetPixelPS(m_Device.GetAPI());

            ShaderDesc desc;
            desc.VertexBlob = vs.Data;
            desc.VertexSize = vs.Size;
            desc.PixelBlob = ps.Data;
            desc.PixelSize = ps.Size;
            desc.VertexEntry = "VSMain";
            desc.PixelEntry = "PSMain";
            desc.DebugName = "Renderer2D Pixel";

            m_PixelShader = Shader::Create(m_Device, desc);
            if (!m_PixelShader)
            {
                LUMINA_LOG_ERROR("Failed to create pixel shader");
                return false;
            }
        }

        // Pixel input layout
        InputLayoutDesc pixelLayoutDesc;
        pixelLayoutDesc.Add("POSITION", Format::RGBA32Float, VertexSemantic::Position)
                       .Add("COLOR", Format::RGBA32Float, VertexSemantic::Color)
                       .Add("PSIZE", Format::RGBA32Float, VertexSemantic::Custom);  // size + _pad[3]

        m_PixelInputLayout = InputLayout::Create(m_Device, pixelLayoutDesc, m_PixelShader);
        if (!m_PixelInputLayout)
        {
            LUMINA_LOG_ERROR("Failed to create pixel input layout");
            return false;
        }

        // Pixel binding layout (just camera constant buffer)
        BindingLayoutDesc pixelBindingDesc;
        pixelBindingDesc.AddConstantBuffer(0);

        m_PixelBindingLayout = BindingLayout::Create(m_Device, pixelBindingDesc);
        if (!m_PixelBindingLayout)
        {
            LUMINA_LOG_ERROR("Failed to create pixel binding layout");
            return false;
        }

        // ========================================================================
        // Create grid resources
        // ========================================================================

        size_t gridVbSize = config.MaxGrids * VerticesPerQuad * sizeof(GridVertex);
        m_GridVertexBuffer = VertexBuffer::Create(m_Device, nullptr, gridVbSize, sizeof(GridVertex), BufferUsage::Dynamic);
        if (!m_GridVertexBuffer)
        {
            LUMINA_LOG_ERROR("Failed to create grid vertex buffer");
            return false;
        }

        // Reuse quad index buffer for grids
        m_GridIndexBuffer = m_QuadIndexBuffer;

        // Grid shader
        {
            auto vs = GetGridVS(m_Device.GetAPI());
            auto ps = GetGridPS(m_Device.GetAPI());

            ShaderDesc desc;
            desc.VertexBlob = vs.Data;
            desc.VertexSize = vs.Size;
            desc.PixelBlob = ps.Data;
            desc.PixelSize = ps.Size;
            desc.VertexEntry = "VSMain";
            desc.PixelEntry = "PSMain";
            desc.DebugName = "Renderer2D Grid";

            m_GridShader = Shader::Create(m_Device, desc);
            if (!m_GridShader)
            {
                LUMINA_LOG_ERROR("Failed to create grid shader");
                return false;
            }
        }

        // Grid input layout (complex - many per-vertex attributes)
        InputLayoutDesc gridLayoutDesc;
        gridLayoutDesc.Add("POSITION", Format::RGBA32Float, VertexSemantic::Position)
                      .Add("LOCALPOS", Format::RGBA32Float, VertexSemantic::Custom)
                      .Add("LINECOLOR", Format::RGBA32Float, VertexSemantic::Custom)
                      .Add("GRIDSIZE", Format::RG32Float, VertexSemantic::Custom)
                      .Add("CELLSIZE", Format::R32Float, VertexSemantic::Custom)
                      .Add("LINEWIDTH", Format::R32Float, VertexSemantic::Custom)
                      .Add("CHECKER", Format::R32Float, VertexSemantic::Custom)
                      .Add("CHECKERCOLOR1", Format::RGBA32Float, VertexSemantic::Custom)
                      .Add("CHECKERCOLOR2", Format::RGBA32Float, VertexSemantic::Custom);

        m_GridInputLayout = InputLayout::Create(m_Device, gridLayoutDesc, m_GridShader);
        if (!m_GridInputLayout)
        {
            LUMINA_LOG_ERROR("Failed to create grid input layout");
            return false;
        }

        // Grid binding layout (just camera constant buffer)
        BindingLayoutDesc gridBindingDesc;
        gridBindingDesc.AddConstantBuffer(0);

        m_GridBindingLayout = BindingLayout::Create(m_Device, gridBindingDesc);
        if (!m_GridBindingLayout)
        {
            LUMINA_LOG_ERROR("Failed to create grid binding layout");
            return false;
        }

        // Pipelines will be created lazily based on render target format

        // Initialize lighting resources
        InitLightingResources();

        m_Initialized = true;

        LUMINA_LOG_INFO("Renderer2D initialized (quads: {}, circles: {}, lines: {}, text: {}, triangles: {}, pixels: {}, grids: {})",
                        config.MaxQuads, config.MaxCircles, config.MaxLines,
                        config.MaxTextChars, config.MaxTriangles, config.MaxPixels, config.MaxGrids);
        return true;
    }

    void Renderer2D::Shutdown()
    {
        if (!m_Initialized)
            return;

        // Shutdown lighting resources
        ShutdownLightingResources();

        // Clear pipelines
        m_QuadPipeline.reset();
        m_CirclePipeline.reset();
        m_LinePipeline.reset();
        m_TextPipeline.reset();
        m_TrianglePipeline.reset();
        m_PixelPipeline.reset();
        m_GridPipeline.reset();

        // Clear binding layouts
        m_QuadBindingLayout.reset();
        m_CircleBindingLayout.reset();
        m_LineBindingLayout.reset();
        m_TextBindingLayout.reset();
        m_TriangleBindingLayout.reset();
        m_PixelBindingLayout.reset();
        m_GridBindingLayout.reset();

        // Clear input layouts
        m_QuadInputLayout.reset();
        m_CircleInputLayout.reset();
        m_LineInputLayout.reset();
        m_TextInputLayout.reset();
        m_TriangleInputLayout.reset();
        m_PixelInputLayout.reset();
        m_GridInputLayout.reset();

        // Clear shaders
        m_QuadShader.reset();
        m_CircleShader.reset();
        m_LineShader.reset();
        m_TextShader.reset();
        m_TriangleShader.reset();
        m_PixelShader.reset();
        m_GridShader.reset();

        // Clear textures
        m_WhiteTexture.reset();
        m_DefaultFont.reset();
        m_CurrentSampler.reset();
        m_PointSampler.reset();
        m_DefaultSampler.reset();

        // Clear buffers
        m_QuadVertexBuffer.reset();
        m_QuadIndexBuffer.reset();
        m_CircleVertexBuffer.reset();
        m_CircleIndexBuffer.reset();
        m_LineVertexBuffer.reset();
        m_TextVertexBuffer.reset();
        m_TextIndexBuffer.reset();
        m_TriangleVertexBuffer.reset();
        m_PixelVertexBuffer.reset();
        m_GridVertexBuffer.reset();
        m_CameraBuffer.reset();

        // Clear binding sets that may hold texture references
        m_FrameBindingSets.clear();

        // Clear render target reference
        m_CurrentTarget.reset();

        // Clear context and pipeline cache
        m_Context.reset();
        m_PipelineCache.reset();

        // Clear layer data
        m_Layers.clear();
        m_PointLights.clear();

        m_Initialized = false;
    }

    void Renderer2D::Begin(const glm::mat4& projection)
    {
        Begin(glm::mat4(1.0f), projection);
    }

    void Renderer2D::Begin(const glm::mat4& view, const glm::mat4& projection)
    {
        LUMINA_PROFILE_SCOPE_NC("Renderer2D::Begin", 0x44FF44);

        // Set up context with current frame's command list
        m_Context->SetCommandList(m_Device.GetCommandList());

        // Clear frame resources from previous frame (keep binding sets alive until now)
        m_FrameBindingSets.clear();

        // Reset vertex buffer offsets for new frame
        m_QuadVertexOffset = 0;
        m_CircleVertexOffset = 0;
        m_LineVertexOffset = 0;
        m_TextVertexOffset = 0;
        m_TriangleVertexOffset = 0;
        m_PixelVertexOffset = 0;
        m_GridVertexOffset = 0;

        // Clear scissor stack for new frame
        while (!m_ScissorStack.empty())
            m_ScissorStack.pop();

        // Auto-set default render target if none is currently set
        if (!m_CurrentTarget && !m_Context->HasFramebuffer())
        {
            SetDefaultRenderTarget();
        }

        m_ViewProjection = projection * view;

        // Update camera constant buffer
        CameraData camData;
        camData.ViewProjection = m_ViewProjection;
        m_CameraBuffer->Update(camData, m_Device.GetCommandList());

        // If lighting is enabled, redirect rendering to the scene target
        if (m_LightingEnabled)
        {
            uint32_t width = m_CurrentTarget ? m_CurrentTarget->GetWidth() : m_Device.GetWidth();
            uint32_t height = m_CurrentTarget ? m_CurrentTarget->GetHeight() : m_Device.GetHeight();

            EnsureLightingTargets(width, height);

            // Render scene to the scene target
            m_Context->SetRenderTarget(m_SceneTarget);
            m_Context->Clear(ClearColor(0.0f, 0.0f, 0.0f, 0.0f));
            m_Context->SetViewport(0, 0, static_cast<float>(width), static_cast<float>(height));

            // Update format tracking for pipeline creation
            m_CurrentColorFormat = m_SceneTarget->GetColorFormat();
            m_CurrentDepthFormat = m_SceneTarget->GetDepthFormat();
        }

        StartBatch();
    }

    void Renderer2D::Begin(const Camera2D& camera)
    {
        Begin(camera.GetViewMatrix(), camera.GetProjectionMatrix());
    }

    void Renderer2D::End()
    {
        LUMINA_PROFILE_SCOPE_NC("Renderer2D::End", 0x44FF44);

        FlushAll();

        // If lighting is enabled, render lights and composite
        if (m_LightingEnabled)
        {
            FlushLights();
            CompositeScene();
        }

        // Resolve MSAA if the current render target uses it
        if (m_CurrentTarget && m_CurrentTarget->IsMsaa())
        {
            m_CurrentTarget->Resolve(m_Context->GetCommandList());
        }
    }

    void Renderer2D::SetRenderTarget(Ref<RenderTarget> target)
    {
        if (m_CurrentTarget != target)
        {
            FlushAll();

            m_CurrentTarget = target;
            m_Context->SetRenderTarget(target);

            if (target)
            {
                m_CurrentColorFormat = target->GetColorFormat();
                m_CurrentDepthFormat = target->GetDepthFormat();
                m_CurrentSampleCount = target->GetSampleCount();

                // Set viewport to match render target size
                m_Context->SetViewport(0, 0,
                    static_cast<float>(target->GetWidth()),
                    static_cast<float>(target->GetHeight()));
            }
        }
    }

    void Renderer2D::SetDefaultRenderTarget()
    {
        FlushAll();

        m_CurrentTarget = nullptr;
        m_Context->SetSwapchainFramebuffer(m_Device.GetCurrentFramebuffer());
        m_Context->SetViewport(0, 0, static_cast<float>(m_Device.GetWidth()), static_cast<float>(m_Device.GetHeight()));

        m_CurrentColorFormat = FromNvrhiFormat(m_Device.GetSwapchainFormat());
        m_CurrentDepthFormat = Format::Unknown;
    }

    void Renderer2D::Clear(const glm::vec4& color)
    {
        m_Context->Clear(ClearColor(color.r, color.g, color.b, color.a));
    }

    void Renderer2D::StartBatch()
    {
        // Clear all layer batches
        for (auto& [layerId, batch] : m_Layers)
        {
            batch.Clear();
            batch.TextureSlots[0] = m_WhiteTexture;
            batch.TextureSlotIndex = 1;
        }

        m_PointLights.clear();
    }

    Renderer2D::LayerBatch& Renderer2D::GetLayer(uint32_t layerId)
    {
        auto it = m_Layers.find(layerId);
        if (it == m_Layers.end())
        {
            // Create new layer batch
            auto& batch = m_Layers[layerId];
            batch.TextureSlots[0] = m_WhiteTexture;
            batch.TextureSlotIndex = 1;
            return batch;
        }
        return it->second;
    }

    float Renderer2D::GetTextureIndex(uint32_t layerId, Ref<Texture> tex)
    {
        auto& batch = GetLayer(layerId);

        // If no texture specified, use white texture
        if (!tex)
            tex = m_WhiteTexture;

        // Check if texture is already bound in this layer
        for (uint32_t i = 0; i < batch.TextureSlotIndex; i++)
        {
            if (batch.TextureSlots[i] == tex)
                return static_cast<float>(i);
        }

        // Need to bind new texture
        if (batch.TextureSlotIndex >= m_Config.MaxTextures)
        {
            // Out of texture slots for this layer, flush and reset texture slots
            // Note: FlushLayer clears vertex data, but we must preserve blend modes
            // which were already set by the caller before calling GetTextureIndex
            BlendMode savedQuadBlend = batch.QuadBlend;
            BlendMode savedCircleBlend = batch.CircleBlend;
            BlendMode savedTriangleBlend = batch.TriangleBlend;

            FlushLayer(layerId);

            // Reset only texture slots - vertex data was cleared by FlushLayer
            batch.TextureSlots.fill(nullptr);
            batch.TextureSlotIndex = 0;

            // Restore blend modes (they may have been set before this call)
            batch.QuadBlend = savedQuadBlend;
            batch.CircleBlend = savedCircleBlend;
            batch.TriangleBlend = savedTriangleBlend;
        }

        batch.TextureSlots[batch.TextureSlotIndex] = tex;
        m_Stats.TextureBinds++;
        return static_cast<float>(batch.TextureSlotIndex++);
    }

    // ========================================================================
    // Drawing implementations
    // ========================================================================

    void Renderer2D::DrawQuad(const QuadDesc& desc)
    {
        uint32_t layerId = static_cast<uint32_t>(desc.Layer);
        auto& batch = GetLayer(layerId);

        // Flush if blend mode changes - must flush lower layers first to maintain order
        if (batch.QuadCount > 0 && batch.QuadBlend != desc.Blend)
        {
            FlushLayersUpTo(layerId);
            FlushQuads(layerId);
            // Note: FlushQuads clears QuadVertices and QuadCount at the end
        }
        batch.QuadBlend = desc.Blend;

        // Flush if batch is full - must flush lower layers first to maintain order
        if (batch.QuadCount >= m_Config.MaxQuads)
        {
            FlushLayersUpTo(layerId);
            FlushQuads(layerId);
            // Note: FlushQuads clears QuadVertices and QuadCount at the end
        }

        float texIndex = GetTextureIndex(layerId, desc.Texture);

        // Calculate corners based on rotation
        glm::vec2 size = desc.Size;
        glm::vec2 origin = desc.Origin * size;
        glm::vec3 pos = desc.Position;

        glm::vec2 p0, p1, p2, p3;

        if (std::abs(desc.Rotation) < 0.0001f)
        {
            // No rotation - simple case
            p0 = glm::vec2(pos) - origin;
            p1 = glm::vec2(pos) + glm::vec2(size.x - origin.x, -origin.y);
            p2 = glm::vec2(pos) + glm::vec2(size.x - origin.x, size.y - origin.y);
            p3 = glm::vec2(pos) + glm::vec2(-origin.x, size.y - origin.y);
        }
        else
        {
            // Rotated quad
            float cosR = std::cos(desc.Rotation);
            float sinR = std::sin(desc.Rotation);

            auto rotate = [&](const glm::vec2& offset) -> glm::vec2 {
                return glm::vec2(pos) + glm::vec2(
                    offset.x * cosR - offset.y * sinR,
                    offset.x * sinR + offset.y * cosR
                );
            };

            p0 = rotate(glm::vec2(-origin.x, -origin.y));
            p1 = rotate(glm::vec2(size.x - origin.x, -origin.y));
            p2 = rotate(glm::vec2(size.x - origin.x, size.y - origin.y));
            p3 = rotate(glm::vec2(-origin.x, size.y - origin.y));
        }

        // Store world positions - GPU will transform via camera buffer
        glm::vec4 world0 = glm::vec4(p0, pos.z, 1.0f);
        glm::vec4 world1 = glm::vec4(p1, pos.z, 1.0f);
        glm::vec4 world2 = glm::vec4(p2, pos.z, 1.0f);
        glm::vec4 world3 = glm::vec4(p3, pos.z, 1.0f);

        // Add vertices (CCW winding) with z_index from desc
        batch.QuadVertices.push_back({ world0, desc.Color, desc.UvMin, texIndex, desc.Z });
        batch.QuadVertices.push_back({ world1, desc.Color, { desc.UvMax.x, desc.UvMin.y }, texIndex, desc.Z });
        batch.QuadVertices.push_back({ world2, desc.Color, desc.UvMax, texIndex, desc.Z });
        batch.QuadVertices.push_back({ world3, desc.Color, { desc.UvMin.x, desc.UvMax.y }, texIndex, desc.Z });

        batch.QuadCount++;
        m_Stats.QuadCount++;
    }

    void Renderer2D::DrawCircle(const CircleDesc& desc)
    {
        uint32_t layerId = static_cast<uint32_t>(desc.Layer);
        auto& batch = GetLayer(layerId);

        // Flush if blend mode changes - must flush lower layers first to maintain order
        if (batch.CircleCount > 0 && batch.CircleBlend != desc.Blend)
        {
            FlushLayersUpTo(layerId);
            FlushCircles(layerId);
            // Note: FlushCircles clears CircleVertices and CircleCount at the end
        }
        batch.CircleBlend = desc.Blend;

        // Flush if batch is full - must flush lower layers first to maintain order
        if (batch.CircleCount >= m_Config.MaxCircles)
        {
            FlushLayersUpTo(layerId);
            FlushCircles(layerId);
            // Note: FlushCircles clears CircleVertices and CircleCount at the end
        }

        float texIndex = GetTextureIndex(layerId, desc.Texture);

        // Circle is rendered as a quad with SDF in shader
        glm::vec2 radius = desc.Radius;
        glm::vec3 pos = desc.Position;

        // Quad corners
        glm::vec2 p0 = glm::vec2(pos) + glm::vec2(-radius.x, -radius.y);
        glm::vec2 p1 = glm::vec2(pos) + glm::vec2( radius.x, -radius.y);
        glm::vec2 p2 = glm::vec2(pos) + glm::vec2( radius.x,  radius.y);
        glm::vec2 p3 = glm::vec2(pos) + glm::vec2(-radius.x,  radius.y);

        // Store world positions - GPU will transform via camera buffer
        glm::vec4 world0 = glm::vec4(p0, pos.z, 1.0f);
        glm::vec4 world1 = glm::vec4(p1, pos.z, 1.0f);
        glm::vec4 world2 = glm::vec4(p2, pos.z, 1.0f);
        glm::vec4 world3 = glm::vec4(p3, pos.z, 1.0f);

        // Local coordinates for SDF (-1 to 1)
        glm::vec4 local0 = glm::vec4(-1.0f, -1.0f, 0.0f, 0.0f);
        glm::vec4 local1 = glm::vec4( 1.0f, -1.0f, 0.0f, 0.0f);
        glm::vec4 local2 = glm::vec4( 1.0f,  1.0f, 0.0f, 0.0f);
        glm::vec4 local3 = glm::vec4(-1.0f,  1.0f, 0.0f, 0.0f);

        // Add vertices with z_index from desc
        CircleVertex v0 = { world0, local0, desc.Color, desc.UvMin, texIndex, desc.Thickness, desc.Fade, desc.Z };
        CircleVertex v1 = { world1, local1, desc.Color, { desc.UvMax.x, desc.UvMin.y }, texIndex, desc.Thickness, desc.Fade, desc.Z };
        CircleVertex v2 = { world2, local2, desc.Color, desc.UvMax, texIndex, desc.Thickness, desc.Fade, desc.Z };
        CircleVertex v3 = { world3, local3, desc.Color, { desc.UvMin.x, desc.UvMax.y }, texIndex, desc.Thickness, desc.Fade, desc.Z };

        batch.CircleVertices.push_back(v0);
        batch.CircleVertices.push_back(v1);
        batch.CircleVertices.push_back(v2);
        batch.CircleVertices.push_back(v3);

        batch.CircleCount++;
        m_Stats.CircleCount++;
    }

    void Renderer2D::DrawLine(const LineDesc& desc)
    {
        uint32_t layerId = static_cast<uint32_t>(desc.Layer);
        auto& batch = GetLayer(layerId);

        // Flush if batch is full - must flush lower layers first to maintain order
        if (batch.LineCount >= m_Config.MaxLines)
        {
            FlushLayersUpTo(layerId);
            FlushLines(layerId);
            batch.LineVertices.clear();
            batch.LineCount = 0;
        }

        if (desc.Thickness <= 1.0f)
        {
            // Simple thin line - store world positions with z_index in w
            glm::vec4 worldStart = glm::vec4(desc.Start, desc.Z);
            glm::vec4 worldEnd = glm::vec4(desc.End, desc.Z);

            batch.LineVertices.push_back({ worldStart, desc.Color });
            batch.LineVertices.push_back({ worldEnd, desc.Color });

            batch.LineCount++;
            m_Stats.LineCount++;
        }
        else
        {
            // Thick line as quad
            glm::vec3 dir = glm::normalize(desc.End - desc.Start);
            glm::vec3 normal = glm::vec3(-dir.y, dir.x, 0.0f) * (desc.Thickness * 0.5f);

            glm::vec3 p0 = desc.Start - normal;
            glm::vec3 p1 = desc.Start + normal;
            glm::vec3 p2 = desc.End + normal;
            glm::vec3 p3 = desc.End - normal;

            DrawQuad({
                .Position = p0,
                .Size = glm::vec2(glm::length(desc.End - desc.Start), desc.Thickness),
                .Color = desc.Color,
                .Rotation = std::atan2(dir.y, dir.x),
                .Origin = {0.0f, 0.5f},
                .Layer = desc.Layer,
                .Z = desc.Z
            });
        }
    }

    void Renderer2D::DrawText(const TextDesc& desc)
    {
        uint32_t layerId = static_cast<uint32_t>(desc.Layer);
        auto& batch = GetLayer(layerId);

        Ref<FontAtlas> font = desc.Font ? desc.Font : m_DefaultFont;
        if (!font)
            return;

        Ref<Texture> fontTex = font->GetTexture();
        float texIndex = GetTextureIndex(layerId, fontTex);

        float scale = desc.Scale;

        glm::vec2 textSize = font->MeasureText(desc.Text);
        float totalWidth = textSize.x * scale;
        float startX = desc.Position.x;

        switch (desc.Alignment)
        {
            case TextAlignment::Center:
                startX -= totalWidth * 0.5f;
                break;
            case TextAlignment::Right:
                startX -= totalWidth;
                break;
            case TextAlignment::Left:
            default:
                break;
        }

        float x = startX;
        float y = desc.Position.y;
        float z = desc.Position.z;

        for (char c : desc.Text)
        {
            // Flush if batch is full - must flush lower layers first to maintain order
            if (batch.TextCharCount >= m_Config.MaxTextChars)
            {
                FlushLayersUpTo(layerId);
                FlushText(layerId);
                batch.TextVertices.clear();
                batch.TextCharCount = 0;
                texIndex = GetTextureIndex(layerId, fontTex);
            }

            const GlyphInfo* glyph = font->GetGlyph(static_cast<uint8_t>(c));
            if (!glyph)
                continue;

            float x0 = x + glyph->X0 * scale;
            float y0 = y + glyph->Y0 * scale;
            float x1 = x + glyph->X1 * scale;
            float y1 = y + glyph->Y1 * scale;

            glm::vec2 p0 = glm::vec2(x0, y0);
            glm::vec2 p1 = glm::vec2(x1, y0);
            glm::vec2 p2 = glm::vec2(x1, y1);
            glm::vec2 p3 = glm::vec2(x0, y1);

            // Store world positions - GPU will transform via camera buffer
            glm::vec4 world0 = glm::vec4(p0, z, 1.0f);
            glm::vec4 world1 = glm::vec4(p1, z, 1.0f);
            glm::vec4 world2 = glm::vec4(p2, z, 1.0f);
            glm::vec4 world3 = glm::vec4(p3, z, 1.0f);

            batch.TextVertices.push_back({ world0, desc.Color, { glyph->U0, glyph->V0 }, texIndex, desc.Z });
            batch.TextVertices.push_back({ world1, desc.Color, { glyph->U1, glyph->V0 }, texIndex, desc.Z });
            batch.TextVertices.push_back({ world2, desc.Color, { glyph->U1, glyph->V1 }, texIndex, desc.Z });
            batch.TextVertices.push_back({ world3, desc.Color, { glyph->U0, glyph->V1 }, texIndex, desc.Z });

            batch.TextCharCount++;
            m_Stats.TextCharCount++;

            x += glyph->AdvanceX * scale;
        }
    }

    void Renderer2D::DrawTriangle(const TriangleDesc& desc)
    {
        uint32_t layerId = static_cast<uint32_t>(desc.Layer);
        auto& batch = GetLayer(layerId);

        // Flush if blend mode changes - must flush lower layers first to maintain order
        if (batch.TriangleCount > 0 && batch.TriangleBlend != desc.Blend)
        {
            FlushLayersUpTo(layerId);
            FlushTriangles(layerId);
            // Note: FlushTriangles clears TriangleVertices and TriangleCount at the end
        }
        batch.TriangleBlend = desc.Blend;

        // Flush if batch is full - must flush lower layers first to maintain order
        if (batch.TriangleCount >= m_Config.MaxTriangles)
        {
            FlushLayersUpTo(layerId);
            FlushTriangles(layerId);
            // Note: FlushTriangles clears TriangleVertices and TriangleCount at the end
        }

        float texIndex = GetTextureIndex(layerId, desc.Texture);

        // Store world positions - GPU will transform via camera buffer
        glm::vec4 world0 = glm::vec4(desc.P0, 1.0f);
        glm::vec4 world1 = glm::vec4(desc.P1, 1.0f);
        glm::vec4 world2 = glm::vec4(desc.P2, 1.0f);

        // Add vertices with z_index from desc
        batch.TriangleVertices.push_back({ world0, desc.Color, desc.Uv0, texIndex, desc.Z });
        batch.TriangleVertices.push_back({ world1, desc.Color, desc.Uv1, texIndex, desc.Z });
        batch.TriangleVertices.push_back({ world2, desc.Color, desc.Uv2, texIndex, desc.Z });

        batch.TriangleCount++;
        m_Stats.TriangleCount++;
    }

    void Renderer2D::DrawPixel(const PixelDesc& desc)
    {
        uint32_t layerId = static_cast<uint32_t>(desc.Layer);
        auto& batch = GetLayer(layerId);

        // Flush if batch is full - must flush lower layers first to maintain order
        if (batch.PixelCount >= m_Config.MaxPixels)
        {
            FlushLayersUpTo(layerId);
            FlushPixels(layerId);
            batch.PixelVertices.clear();
            batch.PixelCount = 0;
        }

        // Store world position with z_index in w
        glm::vec4 worldPos = glm::vec4(desc.Position, desc.Z);

        batch.PixelVertices.push_back({ worldPos, desc.Color, desc.Size, {0, 0, 0} });

        batch.PixelCount++;
        m_Stats.PixelCount++;
    }

    void Renderer2D::DrawRect(const RectDesc& desc)
    {
        // Draw 4 lines forming a rectangle
        glm::vec3 p0 = desc.Position;
        glm::vec3 p1 = desc.Position + glm::vec3(desc.Size.x, 0.0f, 0.0f);
        glm::vec3 p2 = desc.Position + glm::vec3(desc.Size.x, desc.Size.y, 0.0f);
        glm::vec3 p3 = desc.Position + glm::vec3(0.0f, desc.Size.y, 0.0f);

        if (std::abs(desc.Rotation) > 0.0001f)
        {
            // Rotated rectangle
            glm::vec2 center = glm::vec2(desc.Position) + desc.Size * 0.5f;
            float cosR = std::cos(desc.Rotation);
            float sinR = std::sin(desc.Rotation);

            auto rotate = [&](const glm::vec2& p) -> glm::vec3 {
                glm::vec2 offset = p - center;
                return glm::vec3(
                    center.x + offset.x * cosR - offset.y * sinR,
                    center.y + offset.x * sinR + offset.y * cosR,
                    desc.Position.z
                );
            };

            p0 = rotate(glm::vec2(desc.Position));
            p1 = rotate(glm::vec2(desc.Position) + glm::vec2(desc.Size.x, 0.0f));
            p2 = rotate(glm::vec2(desc.Position) + desc.Size);
            p3 = rotate(glm::vec2(desc.Position) + glm::vec2(0.0f, desc.Size.y));
        }

        DrawLine({ .Start = p0, .End = p1, .Color = desc.Color, .Thickness = desc.Thickness, .Layer = desc.Layer });
        DrawLine({ .Start = p1, .End = p2, .Color = desc.Color, .Thickness = desc.Thickness, .Layer = desc.Layer });
        DrawLine({ .Start = p2, .End = p3, .Color = desc.Color, .Thickness = desc.Thickness, .Layer = desc.Layer });
        DrawLine({ .Start = p3, .End = p0, .Color = desc.Color, .Thickness = desc.Thickness, .Layer = desc.Layer });
    }

    void Renderer2D::DrawSprite(const TextureAtlas& atlas, const std::string& regionName, const SpriteDesc& desc)
    {
        const AtlasRegion* region = atlas.GetRegion(regionName);
        if (!region)
        {
            LUMINA_LOG_WARN("Sprite region '{}' not found in atlas", regionName);
            return;
        }

        DrawSprite(*region, atlas.GetTexture(), desc);
    }

    void Renderer2D::DrawSprite(const TextureAtlas& atlas, uint32_t regionIndex, const SpriteDesc& desc)
    {
        const AtlasRegion* region = atlas.GetRegion(regionIndex);
        if (!region)
        {
            LUMINA_LOG_WARN("Sprite region index {} not found in atlas", regionIndex);
            return;
        }

        DrawSprite(*region, atlas.GetTexture(), desc);
    }

    void Renderer2D::DrawSprite(const AtlasRegion& region, Ref<Texture> atlasTexture, const SpriteDesc& desc)
    {
        // Determine size (use region size if not specified)
        glm::vec2 size = desc.Size;
        if (size.x <= 0.0f || size.y <= 0.0f)
        {
            size = region.Size;
        }

        // Handle UV flipping
        glm::vec2 uvMin = region.UvMin;
        glm::vec2 uvMax = region.UvMax;

        if (desc.FlipX)
        {
            std::swap(uvMin.x, uvMax.x);
        }
        if (desc.FlipY)
        {
            std::swap(uvMin.y, uvMax.y);
        }

        // Draw as a textured quad
        QuadDesc quad;
        quad.Position = desc.Position;
        quad.Size = size;
        quad.Color = desc.Color;
        quad.Rotation = desc.Rotation;
        quad.Origin = desc.Origin;
        quad.Texture = atlasTexture;
        quad.UvMin = uvMin;
        quad.UvMax = uvMax;
        quad.Layer = desc.Layer;
        quad.Z = desc.Z;
        quad.Blend = desc.Blend;

        DrawQuad(quad);
    }

    void Renderer2D::DrawGrid(const GridDesc& desc)
    {
        uint32_t layerId = static_cast<uint32_t>(desc.Layer);
        auto& batch = GetLayer(layerId);

        // Flush if batch is full - must flush lower layers first to maintain order
        if (batch.GridCount >= m_Config.MaxGrids)
        {
            FlushLayersUpTo(layerId);
            FlushGrids(layerId);
            batch.GridVertices.clear();
            batch.GridCount = 0;
        }

        // Grid is rendered as a quad with procedural pattern in shader
        glm::vec3 pos = desc.Position;
        glm::vec2 size = desc.Size;

        // Quad corners
        glm::vec2 p0 = glm::vec2(pos);
        glm::vec2 p1 = glm::vec2(pos) + glm::vec2(size.x, 0.0f);
        glm::vec2 p2 = glm::vec2(pos) + size;
        glm::vec2 p3 = glm::vec2(pos) + glm::vec2(0.0f, size.y);

        // Store world positions with z_index in w
        glm::vec4 world0 = glm::vec4(p0, pos.z, desc.Z);
        glm::vec4 world1 = glm::vec4(p1, pos.z, desc.Z);
        glm::vec4 world2 = glm::vec4(p2, pos.z, desc.Z);
        glm::vec4 world3 = glm::vec4(p3, pos.z, desc.Z);

        // Local positions (0 to size for grid calculation)
        glm::vec4 local0 = glm::vec4(0.0f, 0.0f, 0.0f, 0.0f);
        glm::vec4 local1 = glm::vec4(size.x, 0.0f, 0.0f, 0.0f);
        glm::vec4 local2 = glm::vec4(size.x, size.y, 0.0f, 0.0f);
        glm::vec4 local3 = glm::vec4(0.0f, size.y, 0.0f, 0.0f);

        float showChecker = desc.Checkerboard ? 1.0f : 0.0f;

        // Add vertices (all vertices have same grid parameters)
        GridVertex v0 = { world0, local0, desc.LineColor, desc.Size, desc.CellSize, desc.LineWidth, showChecker, desc.CheckerColor1, desc.CheckerColor2 };
        GridVertex v1 = { world1, local1, desc.LineColor, desc.Size, desc.CellSize, desc.LineWidth, showChecker, desc.CheckerColor1, desc.CheckerColor2 };
        GridVertex v2 = { world2, local2, desc.LineColor, desc.Size, desc.CellSize, desc.LineWidth, showChecker, desc.CheckerColor1, desc.CheckerColor2 };
        GridVertex v3 = { world3, local3, desc.LineColor, desc.Size, desc.CellSize, desc.LineWidth, showChecker, desc.CheckerColor1, desc.CheckerColor2 };

        batch.GridVertices.push_back(v0);
        batch.GridVertices.push_back(v1);
        batch.GridVertices.push_back(v2);
        batch.GridVertices.push_back(v3);

        batch.GridCount++;
        m_Stats.GridCount++;
    }

    // ========================================================================
    // Texture Filtering
    // ========================================================================

    void Renderer2D::SetFilterMode(FilterMode mode)
    {
        if (m_FilterMode != mode)
        {
            m_FilterMode = mode;
            m_CurrentSampler = (mode == FilterMode::Point) ? m_PointSampler : m_DefaultSampler;
        }
    }

    // ========================================================================
    // Scissor/Clipping
    // ========================================================================

    void Renderer2D::PushScissor(float x, float y, float width, float height)
    {
        PushScissor(glm::vec4(x, y, width, height));
    }

    void Renderer2D::PushScissor(const glm::vec4& rect)
    {
        // Flush all current primitives before changing scissor state
        FlushAll();

        glm::vec4 newScissor = rect;

        // If there's already a scissor active, intersect with it
        if (!m_ScissorStack.empty())
        {
            const glm::vec4& current = m_ScissorStack.top();

            // Calculate intersection of rectangles
            float x1 = std::max(rect.x, current.x);
            float y1 = std::max(rect.y, current.y);
            float x2 = std::min(rect.x + rect.z, current.x + current.z);
            float y2 = std::min(rect.y + rect.w, current.y + current.w);

            // If no intersection, create a zero-sized rect (nothing will render)
            if (x2 <= x1 || y2 <= y1)
            {
                newScissor = glm::vec4(x1, y1, 0, 0);
            }
            else
            {
                newScissor = glm::vec4(x1, y1, x2 - x1, y2 - y1);
            }
        }

        m_ScissorStack.push(newScissor);
    }

    void Renderer2D::PopScissor()
    {
        if (m_ScissorStack.empty())
        {
            LUMINA_LOG_WARN("PopScissor called with empty scissor stack");
            return;
        }

        // Flush all current primitives before changing scissor state
        FlushAll();

        m_ScissorStack.pop();
    }

    glm::vec4 Renderer2D::GetCurrentScissor() const
    {
        if (m_ScissorStack.empty())
            return glm::vec4(0, 0, 0, 0);
        return m_ScissorStack.top();
    }

    void Renderer2D::ApplyScissor()
    {
        if (m_ScissorStack.empty())
        {
            // No scissor - use full viewport (set to 0,0,0,0 to let context use viewport default)
            m_Context->SetScissor(0, 0, 0, 0);
        }
        else
        {
            const glm::vec4& scissor = m_ScissorStack.top();
            m_Context->SetScissor(
                static_cast<int32_t>(scissor.x),
                static_cast<int32_t>(scissor.y),
                static_cast<int32_t>(scissor.z),
                static_cast<int32_t>(scissor.w)
            );
        }
    }

    // ========================================================================
    // Lighting
    // ========================================================================

    void Renderer2D::SetLightingEnabled(bool enabled)
    {
        m_LightingEnabled = enabled;
    }

    void Renderer2D::SetAmbientLight(const glm::vec3& color, float intensity)
    {
        m_AmbientColor = color;
        m_AmbientIntensity = intensity;
    }

    void Renderer2D::DrawPointLight(const PointLightDesc& desc)
    {
        if (m_PointLights.size() >= m_Config.MaxPointLights)
        {
            LUMINA_LOG_WARN("Maximum point lights ({}) exceeded", m_Config.MaxPointLights);
            return;
        }

        PointLightData light;
        light.Position = desc.Position;
        light.Intensity = desc.Intensity;
        light.Color = desc.Color;
        light.Radius = desc.Radius;
        light.BlendMode = static_cast<float>(desc.Blend);
        light.BlendAlpha = desc.BlendAlpha;
        light.Attenuation = static_cast<float>(desc.Attenuation);
        light.Falloff = desc.Falloff;

        m_PointLights.push_back(light);
        m_Stats.PointLightCount++;
    }

    // ========================================================================
    // Flush methods
    // ========================================================================

    void Renderer2D::FlushAll()
    {
        LUMINA_PROFILE_SCOPE_NC("Renderer2D::FlushAll", 0x44FF44);

        // Iterate layers in sorted order (std::map is ordered by key)
        for (auto& [layerId, batch] : m_Layers)
        {
            if (!batch.IsEmpty())
            {
                FlushLayer(layerId);
            }
        }
    }

    void Renderer2D::FlushLayer(uint32_t layerId)
    {
        LUMINA_PROFILE_SCOPE_NC("Renderer2D::FlushLayer", 0x44FF44);

        // Flush all primitive types for this layer in order
        FlushQuads(layerId);
        FlushCircles(layerId);
        FlushLines(layerId);
        FlushText(layerId);
        FlushTriangles(layerId);
        FlushPixels(layerId);
        FlushGrids(layerId);

        // Reset texture slots after all primitives are flushed
        // This ensures all primitive types can access textures added during the batch
        auto it = m_Layers.find(layerId);
        if (it != m_Layers.end())
        {
            auto& batch = it->second;
            batch.TextureSlots.fill(nullptr);
            batch.TextureSlots[0] = m_WhiteTexture;
            batch.TextureSlotIndex = 1;
        }
    }

    void Renderer2D::FlushLayersUpTo(uint32_t layerId)
    {
        // Flush all layers with IDs less than the given layerId
        // This ensures correct render order when a higher layer needs to flush early
        for (auto& [id, batch] : m_Layers)
        {
            if (id >= layerId)
                break;  // std::map is ordered, so we can stop early
            if (!batch.IsEmpty())
            {
                FlushLayer(id);
            }
        }
    }

    void Renderer2D::FlushQuads(uint32_t layerId)
    {
        LUMINA_PROFILE_SCOPE_NC("Renderer2D::FlushQuads", 0x44FF44);

        auto it = m_Layers.find(layerId);
        if (it == m_Layers.end())
            return;

        auto& batch = it->second;
        if (batch.QuadCount == 0)
            return;

        // Get or create pipeline with correct blend mode (cached to keep alive)
        PipelineDesc desc;
        desc.ShaderProgram = m_QuadShader;
        desc.VertexLayout = m_QuadInputLayout;
        desc.BindingLayouts.push_back(m_QuadBindingLayout);
        desc.State.Blend = batch.QuadBlend;
        desc.State.Depth = DepthMode::None;
        desc.State.Cull = CullMode::None;
        desc.State.Primitive = Topology::Triangles;
        desc.ColorFormat = m_CurrentColorFormat;
        desc.DepthFormat = m_CurrentDepthFormat;
        desc.SampleCount = m_CurrentSampleCount;

        m_QuadPipeline = m_PipelineCache->GetOrCreate(desc);
        if (!m_QuadPipeline)
        {
            LUMINA_LOG_ERROR("Failed to create quad pipeline");
            return;
        }

        // Check if we have room in the vertex buffer
        uint32_t verticesNeeded = batch.QuadCount * VerticesPerQuad;
        if (m_QuadVertexOffset + verticesNeeded > m_Config.MaxQuads * VerticesPerQuad)
        {
            // Buffer is full, reset offset (this may cause issues if GPU hasn't finished previous draws)
            // In practice, this shouldn't happen often with a large enough buffer
            LUMINA_LOG_WARN("Quad vertex buffer full, resetting offset (may cause visual artifacts)");
            m_QuadVertexOffset = 0;
        }

        // Calculate byte offset for vertex data
        size_t offsetBytes = m_QuadVertexOffset * sizeof(QuadVertex);

        // Update vertex buffer at current offset using command list for proper GPU synchronization
        m_QuadVertexBuffer->UpdateAtOffset(batch.QuadVertices.data(), batch.QuadVertices.size() * sizeof(QuadVertex), offsetBytes, m_Context->GetCommandList());

        // Create binding set with camera buffer and all texture slots
        BindingSetDesc bsDesc;
        bsDesc.Layout = m_QuadBindingLayout;
        bsDesc.AddConstantBuffer(0, m_CameraBuffer);

        // Bind all 32 texture slots (fill unused with white texture)
        for (uint32_t i = 0; i < 32; i++)
        {
            Ref<Texture> tex = batch.TextureSlots[i] ? batch.TextureSlots[i] : m_WhiteTexture;
            bsDesc.AddTextureArrayElement(0, i, tex);
        }
        bsDesc.AddSampler(0, m_CurrentSampler);

        auto bindingSet = BindingSet::Create(m_Device, bsDesc);
        if (!bindingSet)
        {
            LUMINA_LOG_ERROR("Failed to create quad binding set");
            return;
        }
        m_FrameBindingSets.push_back(bindingSet);  // Keep alive until frame ends

        // Draw with base vertex offset to read from correct position in vertex buffer
        auto& ctx = *m_Context;
        ctx.SetPipeline(m_QuadPipeline);
        ctx.SetBindingSet(bindingSet);
        ctx.SetVertexBuffer(m_QuadVertexBuffer);
        ctx.SetIndexBuffer(m_QuadIndexBuffer);
        ApplyScissor();
        ctx.DrawIndexed(batch.QuadCount * IndicesPerQuad, 0, static_cast<int32_t>(m_QuadVertexOffset));

        m_Stats.DrawCalls++;

        // Advance vertex offset for next flush
        m_QuadVertexOffset += batch.QuadCount * VerticesPerQuad;

        batch.QuadVertices.clear();
        batch.QuadCount = 0;
        // Note: texture slots are reset at end of FlushLayer, not here
    }

    void Renderer2D::FlushCircles(uint32_t layerId)
    {
        LUMINA_PROFILE_SCOPE_NC("Renderer2D::FlushCircles", 0x44FF44);

        auto it = m_Layers.find(layerId);
        if (it == m_Layers.end())
            return;

        auto& batch = it->second;
        if (batch.CircleCount == 0)
            return;

        // Ensure pipeline exists with correct blend mode and sample count
        if (!m_CirclePipeline ||
            m_CirclePipeline->GetDesc().ColorFormat != m_CurrentColorFormat ||
            m_CirclePipeline->GetDesc().DepthFormat != m_CurrentDepthFormat ||
            m_CirclePipeline->GetDesc().SampleCount != m_CurrentSampleCount ||
            m_CirclePipeline->GetDesc().State.Blend != batch.CircleBlend)
        {
            PipelineDesc desc;
            desc.ShaderProgram = m_CircleShader;
            desc.VertexLayout = m_CircleInputLayout;
            desc.BindingLayouts.push_back(m_CircleBindingLayout);
            desc.State.Blend = batch.CircleBlend;
            desc.State.Depth = DepthMode::None;
            desc.State.Cull = CullMode::None;
            desc.State.Primitive = Topology::Triangles;
            desc.ColorFormat = m_CurrentColorFormat;
            desc.DepthFormat = m_CurrentDepthFormat;
            desc.SampleCount = m_CurrentSampleCount;

            m_CirclePipeline = m_PipelineCache->GetOrCreate(desc);
            if (!m_CirclePipeline)
            {
                LUMINA_LOG_ERROR("Failed to create circle pipeline");
                return;
            }
        }

        // Check if we have room in the vertex buffer
        uint32_t verticesNeeded = batch.CircleCount * VerticesPerQuad;
        if (m_CircleVertexOffset + verticesNeeded > m_Config.MaxCircles * VerticesPerQuad)
        {
            LUMINA_LOG_WARN("Circle vertex buffer full, resetting offset");
            m_CircleVertexOffset = 0;
        }

        // Calculate byte offset and update vertex buffer at current offset
        size_t offsetBytes = m_CircleVertexOffset * sizeof(CircleVertex);
        m_CircleVertexBuffer->UpdateAtOffset(batch.CircleVertices.data(), batch.CircleVertices.size() * sizeof(CircleVertex), offsetBytes, m_Context->GetCommandList());

        // Create binding set with camera buffer and all texture slots
        BindingSetDesc bsDesc;
        bsDesc.Layout = m_CircleBindingLayout;
        bsDesc.AddConstantBuffer(0, m_CameraBuffer);

        // Bind all 32 texture slots (fill unused with white texture)
        for (uint32_t i = 0; i < 32; i++)
        {
            Ref<Texture> tex = batch.TextureSlots[i] ? batch.TextureSlots[i] : m_WhiteTexture;
            bsDesc.AddTextureArrayElement(0, i, tex);
        }
        bsDesc.AddSampler(0, m_CurrentSampler);

        auto bindingSet = BindingSet::Create(m_Device, bsDesc);
        if (!bindingSet)
        {
            LUMINA_LOG_ERROR("Failed to create circle binding set");
            return;
        }
        m_FrameBindingSets.push_back(bindingSet);  // Keep alive until frame ends

        // Draw with base vertex offset
        auto& ctx = *m_Context;
        ctx.SetPipeline(m_CirclePipeline);
        ctx.SetBindingSet(bindingSet);
        ctx.SetVertexBuffer(m_CircleVertexBuffer);
        ctx.SetIndexBuffer(m_CircleIndexBuffer);
        ApplyScissor();
        ctx.DrawIndexed(batch.CircleCount * IndicesPerQuad, 0, static_cast<int32_t>(m_CircleVertexOffset));

        m_Stats.DrawCalls++;

        // Advance vertex offset for next flush
        m_CircleVertexOffset += batch.CircleCount * VerticesPerQuad;

        batch.CircleVertices.clear();
        batch.CircleCount = 0;
    }

    void Renderer2D::FlushLines(uint32_t layerId)
    {
        LUMINA_PROFILE_SCOPE_NC("Renderer2D::FlushLines", 0x44FF44);

        auto it = m_Layers.find(layerId);
        if (it == m_Layers.end())
            return;

        auto& batch = it->second;
        if (batch.LineCount == 0)
            return;

        // Ensure pipeline exists
        if (!m_LinePipeline ||
            m_LinePipeline->GetDesc().ColorFormat != m_CurrentColorFormat ||
            m_LinePipeline->GetDesc().DepthFormat != m_CurrentDepthFormat ||
            m_LinePipeline->GetDesc().SampleCount != m_CurrentSampleCount)
        {
            PipelineDesc desc;
            desc.ShaderProgram = m_LineShader;
            desc.VertexLayout = m_LineInputLayout;
            desc.BindingLayouts.push_back(m_LineBindingLayout);
            desc.State.Blend = BlendMode::Alpha;
            desc.State.Depth = DepthMode::None;
            desc.State.Cull = CullMode::None;
            desc.State.Primitive = Topology::Lines;
            desc.ColorFormat = m_CurrentColorFormat;
            desc.DepthFormat = m_CurrentDepthFormat;
            desc.SampleCount = m_CurrentSampleCount;

            m_LinePipeline = m_PipelineCache->GetOrCreate(desc);
            if (!m_LinePipeline)
            {
                LUMINA_LOG_ERROR("Failed to create line pipeline");
                return;
            }
        }

        // Check if we have room in the vertex buffer (2 vertices per line)
        uint32_t verticesNeeded = batch.LineCount * 2;
        if (m_LineVertexOffset + verticesNeeded > m_Config.MaxLines * 2)
        {
            LUMINA_LOG_WARN("Line vertex buffer full, resetting offset");
            m_LineVertexOffset = 0;
        }

        // Calculate byte offset and update vertex buffer at current offset
        size_t offsetBytes = m_LineVertexOffset * sizeof(LineVertex);
        m_LineVertexBuffer->UpdateAtOffset(batch.LineVertices.data(), batch.LineVertices.size() * sizeof(LineVertex), offsetBytes, m_Context->GetCommandList());

        // Create binding set with camera buffer
        BindingSetDesc bsDesc;
        bsDesc.Layout = m_LineBindingLayout;
        bsDesc.AddConstantBuffer(0, m_CameraBuffer);

        auto bindingSet = BindingSet::Create(m_Device, bsDesc);
        if (!bindingSet)
        {
            LUMINA_LOG_ERROR("Failed to create line binding set");
            return;
        }
        m_FrameBindingSets.push_back(bindingSet);  // Keep alive until frame ends

        // Draw with start vertex offset (lines don't use index buffer)
        auto& ctx = *m_Context;
        ctx.SetPipeline(m_LinePipeline);
        ctx.SetBindingSet(bindingSet);
        ctx.SetVertexBuffer(m_LineVertexBuffer);
        ApplyScissor();
        ctx.Draw(batch.LineCount * 2, m_LineVertexOffset);

        m_Stats.DrawCalls++;

        // Advance vertex offset for next flush
        m_LineVertexOffset += batch.LineCount * 2;

        batch.LineVertices.clear();
        batch.LineCount = 0;
    }

    void Renderer2D::FlushText(uint32_t layerId)
    {
        LUMINA_PROFILE_SCOPE_NC("Renderer2D::FlushText", 0x44FF44);

        auto it = m_Layers.find(layerId);
        if (it == m_Layers.end())
            return;

        auto& batch = it->second;
        if (batch.TextCharCount == 0)
            return;

        // Ensure pipeline exists
        if (!m_TextPipeline ||
            m_TextPipeline->GetDesc().ColorFormat != m_CurrentColorFormat ||
            m_TextPipeline->GetDesc().DepthFormat != m_CurrentDepthFormat ||
            m_TextPipeline->GetDesc().SampleCount != m_CurrentSampleCount)
        {
            PipelineDesc desc;
            desc.ShaderProgram = m_TextShader;
            desc.VertexLayout = m_TextInputLayout;
            desc.BindingLayouts.push_back(m_TextBindingLayout);
            desc.State.Blend = BlendMode::Alpha;
            desc.State.Depth = DepthMode::None;
            desc.State.Cull = CullMode::None;
            desc.State.Primitive = Topology::Triangles;
            desc.ColorFormat = m_CurrentColorFormat;
            desc.DepthFormat = m_CurrentDepthFormat;
            desc.SampleCount = m_CurrentSampleCount;

            m_TextPipeline = m_PipelineCache->GetOrCreate(desc);
            if (!m_TextPipeline)
            {
                LUMINA_LOG_ERROR("Failed to create text pipeline");
                return;
            }
        }

        // Check if we have room in the vertex buffer (4 vertices per character)
        uint32_t verticesNeeded = batch.TextCharCount * VerticesPerQuad;
        if (m_TextVertexOffset + verticesNeeded > m_Config.MaxTextChars * VerticesPerQuad)
        {
            LUMINA_LOG_WARN("Text vertex buffer full, resetting offset");
            m_TextVertexOffset = 0;
        }

        // Calculate byte offset and update vertex buffer at current offset
        size_t offsetBytes = m_TextVertexOffset * sizeof(TextVertex);
        m_TextVertexBuffer->UpdateAtOffset(batch.TextVertices.data(), batch.TextVertices.size() * sizeof(TextVertex), offsetBytes, m_Context->GetCommandList());

        // Create binding set with camera buffer and all texture slots
        BindingSetDesc bsDesc;
        bsDesc.Layout = m_TextBindingLayout;
        bsDesc.AddConstantBuffer(0, m_CameraBuffer);

        // Bind all 32 texture slots (fill unused with white texture)
        for (uint32_t i = 0; i < 32; i++)
        {
            Ref<Texture> tex = batch.TextureSlots[i] ? batch.TextureSlots[i] : m_WhiteTexture;
            bsDesc.AddTextureArrayElement(0, i, tex);
        }
        bsDesc.AddSampler(0, m_CurrentSampler);

        auto bindingSet = BindingSet::Create(m_Device, bsDesc);
        if (!bindingSet)
        {
            LUMINA_LOG_ERROR("Failed to create text binding set");
            return;
        }
        m_FrameBindingSets.push_back(bindingSet);  // Keep alive until frame ends

        // Draw with base vertex offset
        auto& ctx = *m_Context;
        ctx.SetPipeline(m_TextPipeline);
        ctx.SetBindingSet(bindingSet);
        ctx.SetVertexBuffer(m_TextVertexBuffer);
        ctx.SetIndexBuffer(m_TextIndexBuffer);
        ApplyScissor();
        ctx.DrawIndexed(batch.TextCharCount * IndicesPerQuad, 0, static_cast<int32_t>(m_TextVertexOffset));

        m_Stats.DrawCalls++;

        // Advance vertex offset for next flush
        m_TextVertexOffset += batch.TextCharCount * VerticesPerQuad;

        batch.TextVertices.clear();
        batch.TextCharCount = 0;
    }

    void Renderer2D::FlushTriangles(uint32_t layerId)
    {
        LUMINA_PROFILE_SCOPE_NC("Renderer2D::FlushTriangles", 0x44FF44);

        auto it = m_Layers.find(layerId);
        if (it == m_Layers.end())
            return;

        auto& batch = it->second;
        if (batch.TriangleCount == 0)
            return;

        // Ensure pipeline exists with correct blend mode
        if (!m_TrianglePipeline ||
            m_TrianglePipeline->GetDesc().ColorFormat != m_CurrentColorFormat ||
            m_TrianglePipeline->GetDesc().DepthFormat != m_CurrentDepthFormat ||
            m_TrianglePipeline->GetDesc().SampleCount != m_CurrentSampleCount ||
            m_TrianglePipeline->GetDesc().State.Blend != batch.TriangleBlend)
        {
            PipelineDesc desc;
            desc.ShaderProgram = m_TriangleShader;
            desc.VertexLayout = m_TriangleInputLayout;
            desc.BindingLayouts.push_back(m_TriangleBindingLayout);
            desc.State.Blend = batch.TriangleBlend;
            desc.State.Depth = DepthMode::None;
            desc.State.Cull = CullMode::None;
            desc.State.Primitive = Topology::Triangles;
            desc.ColorFormat = m_CurrentColorFormat;
            desc.DepthFormat = m_CurrentDepthFormat;
            desc.SampleCount = m_CurrentSampleCount;

            m_TrianglePipeline = m_PipelineCache->GetOrCreate(desc);
            if (!m_TrianglePipeline)
            {
                LUMINA_LOG_ERROR("Failed to create triangle pipeline");
                return;
            }
        }

        // Check if we have room in the vertex buffer (3 vertices per triangle)
        uint32_t verticesNeeded = batch.TriangleCount * 3;
        if (m_TriangleVertexOffset + verticesNeeded > m_Config.MaxTriangles * 3)
        {
            LUMINA_LOG_WARN("Triangle vertex buffer full, resetting offset");
            m_TriangleVertexOffset = 0;
        }

        // Calculate byte offset and update vertex buffer at current offset
        size_t offsetBytes = m_TriangleVertexOffset * sizeof(TriangleVertex);
        m_TriangleVertexBuffer->UpdateAtOffset(batch.TriangleVertices.data(), batch.TriangleVertices.size() * sizeof(TriangleVertex), offsetBytes, m_Context->GetCommandList());

        // Create binding set with camera buffer and all texture slots
        BindingSetDesc bsDesc;
        bsDesc.Layout = m_TriangleBindingLayout;
        bsDesc.AddConstantBuffer(0, m_CameraBuffer);

        // Bind all 32 texture slots (fill unused with white texture)
        for (uint32_t i = 0; i < 32; i++)
        {
            Ref<Texture> tex = batch.TextureSlots[i] ? batch.TextureSlots[i] : m_WhiteTexture;
            bsDesc.AddTextureArrayElement(0, i, tex);
        }
        bsDesc.AddSampler(0, m_CurrentSampler);

        auto bindingSet = BindingSet::Create(m_Device, bsDesc);
        if (!bindingSet)
        {
            LUMINA_LOG_ERROR("Failed to create triangle binding set");
            return;
        }
        m_FrameBindingSets.push_back(bindingSet);  // Keep alive until frame ends

        // Draw with start vertex offset (no index buffer - raw triangles)
        auto& ctx = *m_Context;
        ctx.SetPipeline(m_TrianglePipeline);
        ctx.SetBindingSet(bindingSet);
        ctx.SetVertexBuffer(m_TriangleVertexBuffer);
        ApplyScissor();
        ctx.Draw(batch.TriangleCount * 3, m_TriangleVertexOffset);

        m_Stats.DrawCalls++;

        // Advance vertex offset for next flush
        m_TriangleVertexOffset += batch.TriangleCount * 3;

        batch.TriangleVertices.clear();
        batch.TriangleCount = 0;
    }

    void Renderer2D::FlushPixels(uint32_t layerId)
    {
        LUMINA_PROFILE_SCOPE_NC("Renderer2D::FlushPixels", 0x44FF44);

        auto it = m_Layers.find(layerId);
        if (it == m_Layers.end())
            return;

        auto& batch = it->second;
        if (batch.PixelCount == 0)
            return;

        // Ensure pipeline exists
        if (!m_PixelPipeline ||
            m_PixelPipeline->GetDesc().ColorFormat != m_CurrentColorFormat ||
            m_PixelPipeline->GetDesc().DepthFormat != m_CurrentDepthFormat ||
            m_PixelPipeline->GetDesc().SampleCount != m_CurrentSampleCount)
        {
            PipelineDesc desc;
            desc.ShaderProgram = m_PixelShader;
            desc.VertexLayout = m_PixelInputLayout;
            desc.BindingLayouts.push_back(m_PixelBindingLayout);
            desc.State.Blend = BlendMode::Alpha;
            desc.State.Depth = DepthMode::None;
            desc.State.Cull = CullMode::None;
            desc.State.Primitive = Topology::Points;
            desc.ColorFormat = m_CurrentColorFormat;
            desc.DepthFormat = m_CurrentDepthFormat;
            desc.SampleCount = m_CurrentSampleCount;

            m_PixelPipeline = m_PipelineCache->GetOrCreate(desc);
            if (!m_PixelPipeline)
            {
                LUMINA_LOG_ERROR("Failed to create pixel pipeline");
                return;
            }
        }

        // Check if we have room in the vertex buffer
        uint32_t maxVertices = m_Config.MaxPixels;
        if (m_PixelVertexOffset + batch.PixelCount > maxVertices)
        {
            LUMINA_LOG_WARN("Pixel vertex buffer full, resetting offset (may cause visual artifacts)");
            m_PixelVertexOffset = 0;
        }

        // Update vertex buffer at current offset
        size_t byteOffset = m_PixelVertexOffset * sizeof(PixelVertex);
        m_PixelVertexBuffer->UpdateAtOffset(batch.PixelVertices.data(), batch.PixelVertices.size() * sizeof(PixelVertex), byteOffset, m_Context->GetCommandList());

        // Create binding set with camera buffer
        BindingSetDesc bsDesc;
        bsDesc.Layout = m_PixelBindingLayout;
        bsDesc.AddConstantBuffer(0, m_CameraBuffer);

        auto bindingSet = BindingSet::Create(m_Device, bsDesc);
        if (!bindingSet)
        {
            LUMINA_LOG_ERROR("Failed to create pixel binding set");
            return;
        }
        m_FrameBindingSets.push_back(bindingSet);  // Keep alive until frame ends

        // Draw with start_vertex offset
        auto& ctx = *m_Context;
        ctx.SetPipeline(m_PixelPipeline);
        ctx.SetBindingSet(bindingSet);
        ctx.SetVertexBuffer(m_PixelVertexBuffer);
        ApplyScissor();
        ctx.Draw(batch.PixelCount, m_PixelVertexOffset);

        m_Stats.DrawCalls++;

        // Advance vertex offset for next flush
        m_PixelVertexOffset += batch.PixelCount;

        batch.PixelVertices.clear();
        batch.PixelCount = 0;
    }

    void Renderer2D::FlushGrids(uint32_t layerId)
    {
        LUMINA_PROFILE_SCOPE_NC("Renderer2D::FlushGrids", 0x44FF44);

        auto it = m_Layers.find(layerId);
        if (it == m_Layers.end())
            return;

        auto& batch = it->second;
        if (batch.GridCount == 0)
            return;

        // Ensure pipeline exists
        if (!m_GridPipeline ||
            m_GridPipeline->GetDesc().ColorFormat != m_CurrentColorFormat ||
            m_GridPipeline->GetDesc().DepthFormat != m_CurrentDepthFormat ||
            m_GridPipeline->GetDesc().SampleCount != m_CurrentSampleCount)
        {
            PipelineDesc desc;
            desc.ShaderProgram = m_GridShader;
            desc.VertexLayout = m_GridInputLayout;
            desc.BindingLayouts.push_back(m_GridBindingLayout);
            desc.State.Blend = BlendMode::Alpha;
            desc.State.Depth = DepthMode::None;
            desc.State.Cull = CullMode::None;
            desc.State.Primitive = Topology::Triangles;
            desc.ColorFormat = m_CurrentColorFormat;
            desc.DepthFormat = m_CurrentDepthFormat;
            desc.SampleCount = m_CurrentSampleCount;

            m_GridPipeline = m_PipelineCache->GetOrCreate(desc);
            if (!m_GridPipeline)
            {
                LUMINA_LOG_ERROR("Failed to create grid pipeline");
                return;
            }
        }

        // Check if we have room in the vertex buffer
        uint32_t verticesNeeded = batch.GridCount * VerticesPerQuad;
        uint32_t maxVertices = m_Config.MaxGrids * VerticesPerQuad;
        if (m_GridVertexOffset + verticesNeeded > maxVertices)
        {
            LUMINA_LOG_WARN("Grid vertex buffer full, resetting offset (may cause visual artifacts)");
            m_GridVertexOffset = 0;
        }

        // Update vertex buffer at current offset
        size_t byteOffset = m_GridVertexOffset * sizeof(GridVertex);
        m_GridVertexBuffer->UpdateAtOffset(batch.GridVertices.data(), batch.GridVertices.size() * sizeof(GridVertex), byteOffset, m_Context->GetCommandList());

        // Create binding set with camera buffer
        BindingSetDesc bsDesc;
        bsDesc.Layout = m_GridBindingLayout;
        bsDesc.AddConstantBuffer(0, m_CameraBuffer);

        auto bindingSet = BindingSet::Create(m_Device, bsDesc);
        if (!bindingSet)
        {
            LUMINA_LOG_ERROR("Failed to create grid binding set");
            return;
        }
        m_FrameBindingSets.push_back(bindingSet);  // Keep alive until frame ends

        // Draw with base_vertex offset for indexed drawing
        auto& ctx = *m_Context;
        ctx.SetPipeline(m_GridPipeline);
        ctx.SetBindingSet(bindingSet);
        ctx.SetVertexBuffer(m_GridVertexBuffer);
        ctx.SetIndexBuffer(m_GridIndexBuffer);
        ApplyScissor();
        ctx.DrawIndexed(batch.GridCount * IndicesPerQuad, 0, m_GridVertexOffset);

        m_Stats.DrawCalls++;

        // Advance vertex offset for next flush
        m_GridVertexOffset += verticesNeeded;

        batch.GridVertices.clear();
        batch.GridCount = 0;
    }

    // ========================================================================
    // Lighting Implementation
    // ========================================================================

    void Renderer2D::InitLightingResources()
    {
        // Create fullscreen quad vertex buffer (NDC coordinates)
        FullscreenVertex fullscreenVerts[4] = {
            {{ -1.0f, -1.0f, 0.0f, 1.0f }, { 0.0f, 1.0f }},  // Bottom-left
            {{  1.0f, -1.0f, 0.0f, 1.0f }, { 1.0f, 1.0f }},  // Bottom-right
            {{  1.0f,  1.0f, 0.0f, 1.0f }, { 1.0f, 0.0f }},  // Top-right
            {{ -1.0f,  1.0f, 0.0f, 1.0f }, { 0.0f, 0.0f }},  // Top-left
        };

        m_FullscreenVertexBuffer = VertexBuffer::Create(m_Device, fullscreenVerts, sizeof(fullscreenVerts), sizeof(FullscreenVertex), BufferUsage::Immutable);
        if (!m_FullscreenVertexBuffer)
        {
            LUMINA_LOG_ERROR("Failed to create fullscreen vertex buffer");
            return;
        }

        // Point light shader
        {
            auto vs = GetPointLightVS(m_Device.GetAPI());
            auto ps = GetPointLightPS(m_Device.GetAPI());

            ShaderDesc desc;
            desc.VertexBlob = vs.Data;
            desc.VertexSize = vs.Size;
            desc.PixelBlob = ps.Data;
            desc.PixelSize = ps.Size;
            desc.VertexEntry = "VSMain";
            desc.PixelEntry = "PSMain";
            desc.DebugName = "Point Light";

            m_PointLightShader = Shader::Create(m_Device, desc);
            if (!m_PointLightShader)
            {
                LUMINA_LOG_ERROR("Failed to create point light shader");
                return;
            }
        }

        // Point light input layout
        InputLayoutDesc lightLayoutDesc;
        lightLayoutDesc.Add("POSITION", Format::RGBA32Float, VertexSemantic::Position)
                       .Add("TEXCOORD", Format::RG32Float, VertexSemantic::Texcoord);

        m_PointLightInputLayout = InputLayout::Create(m_Device, lightLayoutDesc, m_PointLightShader);
        if (!m_PointLightInputLayout)
        {
            LUMINA_LOG_ERROR("Failed to create point light input layout");
            return;
        }

        // Point light binding layout (constant buffer only)
        BindingLayoutDesc lightBindingDesc;
        lightBindingDesc.AddConstantBuffer(0);

        m_PointLightBindingLayout = BindingLayout::Create(m_Device, lightBindingDesc);
        if (!m_PointLightBindingLayout)
        {
            LUMINA_LOG_ERROR("Failed to create point light binding layout");
            return;
        }

        // Point light constant buffer
        // Structure: float2 position, float2 viewport_size, float3 color, float intensity,
        //            float radius, float attenuation, float falloff, float pad, mat4 inv_view_proj
        m_LightParamsBuffer = UniformBuffer::Create(m_Device, 128); // Generous size for alignment
        if (!m_LightParamsBuffer)
        {
            LUMINA_LOG_ERROR("Failed to create light params buffer");
            return;
        }

        // Composite shader
        {
            auto vs = GetCompositeVS(m_Device.GetAPI());
            auto ps = GetCompositePS(m_Device.GetAPI());

            ShaderDesc desc;
            desc.VertexBlob = vs.Data;
            desc.VertexSize = vs.Size;
            desc.PixelBlob = ps.Data;
            desc.PixelSize = ps.Size;
            desc.VertexEntry = "VSMain";
            desc.PixelEntry = "PSMain";
            desc.DebugName = "Composite";

            m_CompositeShader = Shader::Create(m_Device, desc);
            if (!m_CompositeShader)
            {
                LUMINA_LOG_ERROR("Failed to create composite shader");
                return;
            }
        }

        // Composite input layout (same as point light)
        m_CompositeInputLayout = m_PointLightInputLayout;

        // Composite binding layout (constant buffer + 2 textures + sampler)
        BindingLayoutDesc compositeBindingDesc;
        compositeBindingDesc.AddConstantBuffer(0);
        compositeBindingDesc.AddTexture(0);  // Scene texture
        compositeBindingDesc.AddTexture(1);  // Light texture
        compositeBindingDesc.AddSampler(0);

        m_CompositeBindingLayout = BindingLayout::Create(m_Device, compositeBindingDesc);
        if (!m_CompositeBindingLayout)
        {
            LUMINA_LOG_ERROR("Failed to create composite binding layout");
            return;
        }

        // Composite constant buffer
        // Structure: float3 ambient_color, float ambient_intensity
        m_CompositeParamsBuffer = UniformBuffer::Create(m_Device, 32);
        if (!m_CompositeParamsBuffer)
        {
            LUMINA_LOG_ERROR("Failed to create composite params buffer");
            return;
        }

        LUMINA_LOG_INFO("Lighting resources initialized");
    }

    void Renderer2D::ShutdownLightingResources()
    {
        m_SceneTarget.reset();
        m_LightAccumulation.reset();
        m_FullscreenVertexBuffer.reset();
        m_PointLightShader.reset();
        m_PointLightInputLayout.reset();
        m_PointLightBindingLayout.reset();
        m_PointLightPipeline.reset();
        m_CompositeShader.reset();
        m_CompositeInputLayout.reset();
        m_CompositeBindingLayout.reset();
        m_CompositePipeline.reset();
        m_LightParamsBuffer.reset();
        m_CompositeParamsBuffer.reset();

        m_LightingTargetWidth = 0;
        m_LightingTargetHeight = 0;
    }

    void Renderer2D::EnsureLightingTargets(uint32_t width, uint32_t height)
    {
        if (m_LightingTargetWidth == width && m_LightingTargetHeight == height)
            return;

        // Create or resize scene target
        if (!m_SceneTarget || m_SceneTarget->GetWidth() != width || m_SceneTarget->GetHeight() != height)
        {
            m_SceneTarget = RenderTarget::Create(m_Device, width, height, Format::RGBA16Float);
            if (!m_SceneTarget)
            {
                LUMINA_LOG_ERROR("Failed to create scene render target for lighting");
                return;
            }
        }

        // Create or resize light accumulation target
        if (!m_LightAccumulation || m_LightAccumulation->GetWidth() != width || m_LightAccumulation->GetHeight() != height)
        {
            m_LightAccumulation = RenderTarget::Create(m_Device, width, height, Format::RGBA16Float);
            if (!m_LightAccumulation)
            {
                LUMINA_LOG_ERROR("Failed to create light accumulation render target");
                return;
            }
        }

        m_LightingTargetWidth = width;
        m_LightingTargetHeight = height;

        LUMINA_LOG_INFO("Lighting targets resized to {}x{}", width, height);
    }

    void Renderer2D::FlushLights()
    {
        LUMINA_PROFILE_SCOPE_NC("Renderer2D::FlushLights", 0x44FF44);

        if (m_PointLights.empty())
            return;

        // Ensure point light pipeline exists
        if (!m_PointLightPipeline)
        {
            PipelineDesc desc;
            desc.ShaderProgram = m_PointLightShader;
            desc.VertexLayout = m_PointLightInputLayout;
            desc.BindingLayouts.push_back(m_PointLightBindingLayout);
            desc.State.Blend = BlendMode::Additive;  // Additive blending for light accumulation
            desc.State.Depth = DepthMode::None;
            desc.State.Cull = CullMode::None;
            desc.State.Primitive = Topology::Triangles;
            desc.ColorFormat = m_LightAccumulation ? m_LightAccumulation->GetColorFormat() : Format::RGBA16Float;
            desc.DepthFormat = Format::Unknown;

            m_PointLightPipeline = m_PipelineCache->GetOrCreate(desc);
            if (!m_PointLightPipeline)
            {
                LUMINA_LOG_ERROR("Failed to create point light pipeline");
                return;
            }
        }

        // Clear light accumulation buffer
        m_Context->SetRenderTarget(m_LightAccumulation);
        m_Context->Clear(ClearColor(0.0f, 0.0f, 0.0f, 0.0f));

        // Calculate inverse view-projection matrix
        glm::mat4 invViewProj = glm::inverse(m_ViewProjection);

        // Render each point light
        for (const auto& light : m_PointLights)
        {
            // Light params structure (must match HLSL cbuffer layout)
            struct alignas(16) LightParams
            {
                glm::vec2 Position;
                glm::vec2 ViewportSize;
                glm::vec3 Color;
                float Intensity;
                float Radius;
                float AttenuationModel;
                float Falloff;
                float Pad;
                glm::mat4 InvViewProj;
            };

            LightParams params;
            params.Position = glm::vec2(light.Position.x, light.Position.y);
            params.ViewportSize = glm::vec2(static_cast<float>(m_LightingTargetWidth), static_cast<float>(m_LightingTargetHeight));
            params.Color = light.Color;
            params.Intensity = light.Intensity;
            params.Radius = light.Radius;
            params.AttenuationModel = light.Attenuation;
            params.Falloff = light.Falloff;
            params.Pad = 0.0f;
            params.InvViewProj = invViewProj;

            // Update constant buffer
            m_LightParamsBuffer->Update(params, m_Device.GetCommandList());

            // Create binding set for this light
            BindingSetDesc bsDesc;
            bsDesc.Layout = m_PointLightBindingLayout;
            bsDesc.AddConstantBuffer(0, m_LightParamsBuffer);

            auto bindingSet = BindingSet::Create(m_Device, bsDesc);
            if (!bindingSet)
            {
                LUMINA_LOG_ERROR("Failed to create point light binding set");
                continue;
            }
            m_FrameBindingSets.push_back(bindingSet);  // Keep alive until frame ends

            // Draw fullscreen quad
            auto& ctx = *m_Context;
            ctx.SetPipeline(m_PointLightPipeline);
            ctx.SetBindingSet(bindingSet);
            ctx.SetVertexBuffer(m_FullscreenVertexBuffer);
            ctx.SetIndexBuffer(m_QuadIndexBuffer); // Reuse quad index buffer
            ctx.DrawIndexed(6);

            m_Stats.DrawCalls++;
        }
    }

    void Renderer2D::CompositeScene()
    {
        if (!m_SceneTarget || !m_LightAccumulation)
            return;

        // Ensure composite pipeline exists
        if (!m_CompositePipeline)
        {
            PipelineDesc desc;
            desc.ShaderProgram = m_CompositeShader;
            desc.VertexLayout = m_CompositeInputLayout;
            desc.BindingLayouts.push_back(m_CompositeBindingLayout);
            desc.State.Blend = BlendMode::Alpha;
            desc.State.Depth = DepthMode::None;
            desc.State.Cull = CullMode::None;
            desc.State.Primitive = Topology::Triangles;
            desc.ColorFormat = m_CurrentColorFormat;
            desc.DepthFormat = m_CurrentDepthFormat;
            desc.SampleCount = m_CurrentSampleCount;

            m_CompositePipeline = m_PipelineCache->GetOrCreate(desc);
            if (!m_CompositePipeline)
            {
                LUMINA_LOG_ERROR("Failed to create composite pipeline");
                return;
            }
        }

        // Composite params structure (must match HLSL cbuffer layout)
        struct alignas(16) CompositeParams
        {
            glm::vec3 AmbientColor;
            float AmbientIntensity;
        };

        CompositeParams params;
        params.AmbientColor = m_AmbientColor;
        params.AmbientIntensity = m_AmbientIntensity;

        // Update constant buffer
        m_CompositeParamsBuffer->Update(params, m_Device.GetCommandList());

        // Set render target back to original (swapchain or user target)
        if (m_CurrentTarget)
        {
            m_Context->SetRenderTarget(m_CurrentTarget);
        }
        else
        {
            m_Context->SetSwapchainFramebuffer(m_Device.GetCurrentFramebuffer());
        }

        // Create binding set
        BindingSetDesc bsDesc;
        bsDesc.Layout = m_CompositeBindingLayout;
        bsDesc.AddConstantBuffer(0, m_CompositeParamsBuffer);
        bsDesc.AddTexture(0, m_SceneTarget->GetColorTexture());
        bsDesc.AddTexture(1, m_LightAccumulation->GetColorTexture());
        bsDesc.AddSampler(0, m_CurrentSampler);

        auto bindingSet = BindingSet::Create(m_Device, bsDesc);
        if (!bindingSet)
        {
            LUMINA_LOG_ERROR("Failed to create composite binding set");
            return;
        }
        m_FrameBindingSets.push_back(bindingSet);  // Keep alive until frame ends

        // Draw fullscreen quad
        auto& ctx = *m_Context;
        ctx.SetPipeline(m_CompositePipeline);
        ctx.SetBindingSet(bindingSet);
        ctx.SetVertexBuffer(m_FullscreenVertexBuffer);
        ctx.SetIndexBuffer(m_QuadIndexBuffer);
        ctx.DrawIndexed(6);

        m_Stats.DrawCalls++;
    }
}
