#include "renderer2d.h"
#include "context.h"
#include "format_utils.h"

#include <lumina/core/device.h>
#include "embedded_font.h"

#include <lumina/core/log.h>

#include <glm/gtc/matrix_transform.hpp>

// Embedded shader bytecode (generated by compile-shaders script)
#include "shaders/quad_vs.h"
#include "shaders/quad_ps.h"
#include "shaders/line_vs.h"
#include "shaders/line_ps.h"
#include "shaders/circle_vs.h"
#include "shaders/circle_ps.h"
#include "shaders/text_vs.h"
#include "shaders/text_ps.h"
#include "shaders/triangle_vs.h"
#include "shaders/triangle_ps.h"
#include "shaders/pixel_vs.h"
#include "shaders/pixel_ps.h"
#include "shaders/grid_vs.h"
#include "shaders/grid_ps.h"
#include "shaders/point_light_vs.h"
#include "shaders/point_light_ps.h"
#include "shaders/composite_vs.h"
#include "shaders/composite_ps.h"

namespace
{
    // Helper to get correct bytecode for current backend
    struct shader_bytecode
    {
        const void* data;
        size_t size;
    };

    // Quad shaders
    shader_bytecode get_quad_vs(lumina::core::graphics_api api)
    {
        if (api == lumina::core::graphics_api::d3d12)
            return { g_quad_vs_dxil, sizeof(g_quad_vs_dxil) };
        else
            return { g_quad_vs_spirv, sizeof(g_quad_vs_spirv) };
    }

    shader_bytecode get_quad_ps(lumina::core::graphics_api api)
    {
        if (api == lumina::core::graphics_api::d3d12)
            return { g_quad_ps_dxil, sizeof(g_quad_ps_dxil) };
        else
            return { g_quad_ps_spirv, sizeof(g_quad_ps_spirv) };
    }

    // Line shaders
    shader_bytecode get_line_vs(lumina::core::graphics_api api)
    {
        if (api == lumina::core::graphics_api::d3d12)
            return { g_line_vs_dxil, sizeof(g_line_vs_dxil) };
        else
            return { g_line_vs_spirv, sizeof(g_line_vs_spirv) };
    }

    shader_bytecode get_line_ps(lumina::core::graphics_api api)
    {
        if (api == lumina::core::graphics_api::d3d12)
            return { g_line_ps_dxil, sizeof(g_line_ps_dxil) };
        else
            return { g_line_ps_spirv, sizeof(g_line_ps_spirv) };
    }

    // Circle shaders
    shader_bytecode get_circle_vs(lumina::core::graphics_api api)
    {
        if (api == lumina::core::graphics_api::d3d12)
            return { g_circle_vs_dxil, sizeof(g_circle_vs_dxil) };
        else
            return { g_circle_vs_spirv, sizeof(g_circle_vs_spirv) };
    }

    shader_bytecode get_circle_ps(lumina::core::graphics_api api)
    {
        if (api == lumina::core::graphics_api::d3d12)
            return { g_circle_ps_dxil, sizeof(g_circle_ps_dxil) };
        else
            return { g_circle_ps_spirv, sizeof(g_circle_ps_spirv) };
    }

    // Text shaders
    shader_bytecode get_text_vs(lumina::core::graphics_api api)
    {
        if (api == lumina::core::graphics_api::d3d12)
            return { g_text_vs_dxil, sizeof(g_text_vs_dxil) };
        else
            return { g_text_vs_spirv, sizeof(g_text_vs_spirv) };
    }

    shader_bytecode get_text_ps(lumina::core::graphics_api api)
    {
        if (api == lumina::core::graphics_api::d3d12)
            return { g_text_ps_dxil, sizeof(g_text_ps_dxil) };
        else
            return { g_text_ps_spirv, sizeof(g_text_ps_spirv) };
    }

    // Triangle shaders
    shader_bytecode get_triangle_vs(lumina::core::graphics_api api)
    {
        if (api == lumina::core::graphics_api::d3d12)
            return { g_triangle_vs_dxil, sizeof(g_triangle_vs_dxil) };
        else
            return { g_triangle_vs_spirv, sizeof(g_triangle_vs_spirv) };
    }

    shader_bytecode get_triangle_ps(lumina::core::graphics_api api)
    {
        if (api == lumina::core::graphics_api::d3d12)
            return { g_triangle_ps_dxil, sizeof(g_triangle_ps_dxil) };
        else
            return { g_triangle_ps_spirv, sizeof(g_triangle_ps_spirv) };
    }

    // Pixel shaders
    shader_bytecode get_pixel_vs(lumina::core::graphics_api api)
    {
        if (api == lumina::core::graphics_api::d3d12)
            return { g_pixel_vs_dxil, sizeof(g_pixel_vs_dxil) };
        else
            return { g_pixel_vs_spirv, sizeof(g_pixel_vs_spirv) };
    }

    shader_bytecode get_pixel_ps(lumina::core::graphics_api api)
    {
        if (api == lumina::core::graphics_api::d3d12)
            return { g_pixel_ps_dxil, sizeof(g_pixel_ps_dxil) };
        else
            return { g_pixel_ps_spirv, sizeof(g_pixel_ps_spirv) };
    }

    // Grid shaders
    shader_bytecode get_grid_vs(lumina::core::graphics_api api)
    {
        if (api == lumina::core::graphics_api::d3d12)
            return { g_grid_vs_dxil, sizeof(g_grid_vs_dxil) };
        else
            return { g_grid_vs_spirv, sizeof(g_grid_vs_spirv) };
    }

    shader_bytecode get_grid_ps(lumina::core::graphics_api api)
    {
        if (api == lumina::core::graphics_api::d3d12)
            return { g_grid_ps_dxil, sizeof(g_grid_ps_dxil) };
        else
            return { g_grid_ps_spirv, sizeof(g_grid_ps_spirv) };
    }

    // Point light shaders
    shader_bytecode get_point_light_vs(lumina::core::graphics_api api)
    {
        if (api == lumina::core::graphics_api::d3d12)
            return { g_point_light_vs_dxil, sizeof(g_point_light_vs_dxil) };
        else
            return { g_point_light_vs_spirv, sizeof(g_point_light_vs_spirv) };
    }

    shader_bytecode get_point_light_ps(lumina::core::graphics_api api)
    {
        if (api == lumina::core::graphics_api::d3d12)
            return { g_point_light_ps_dxil, sizeof(g_point_light_ps_dxil) };
        else
            return { g_point_light_ps_spirv, sizeof(g_point_light_ps_spirv) };
    }

    // Composite shaders
    shader_bytecode get_composite_vs(lumina::core::graphics_api api)
    {
        if (api == lumina::core::graphics_api::d3d12)
            return { g_composite_vs_dxil, sizeof(g_composite_vs_dxil) };
        else
            return { g_composite_vs_spirv, sizeof(g_composite_vs_spirv) };
    }

    shader_bytecode get_composite_ps(lumina::core::graphics_api api)
    {
        if (api == lumina::core::graphics_api::d3d12)
            return { g_composite_ps_dxil, sizeof(g_composite_ps_dxil) };
        else
            return { g_composite_ps_spirv, sizeof(g_composite_ps_spirv) };
    }
}

namespace lumina::graphics
{
    renderer2d::renderer2d(core::device& dev)
        : m_device(dev)
    {
    }

    renderer2d::~renderer2d()
    {
        shutdown();
    }

    bool renderer2d::init(const renderer2d_config& config)
    {
        if (m_initialized)
            return true;

        m_config = config;

        // Create rendering context
        m_context = lumina::make_scope<context>(m_device);
        if (!m_context)
        {
            LUMINA_LOG_ERROR("Failed to create rendering context");
            return false;
        }

        // Create pipeline cache to keep pipelines alive across flushes
        m_pipeline_cache = lumina::make_scope<pipeline_cache>(m_device);

        // Reserve point lights storage (layers are created on-demand)
        m_point_lights.reserve(config.max_point_lights);

        // ========================================================================
        // Create shared resources
        // ========================================================================

        // Default sampler (linear)
        m_default_sampler = sampler::create(m_device, samplers::linear_clamp());
        if (!m_default_sampler)
        {
            LUMINA_LOG_ERROR("Failed to create default sampler");
            return false;
        }

        // Point sampler (for pixel art)
        m_point_sampler = sampler::create(m_device, samplers::point_clamp());
        if (!m_point_sampler)
        {
            LUMINA_LOG_ERROR("Failed to create point sampler");
            return false;
        }

        // Set current sampler to default (linear)
        m_current_sampler = m_default_sampler;
        m_filter_mode = filter_mode::linear;

        // 1x1 white texture
        uint32_t white_pixel = 0xFFFFFFFF;
        m_white_texture = texture::create(m_device, 1, 1, format::rgba8_unorm, &white_pixel);
        if (!m_white_texture)
        {
            LUMINA_LOG_ERROR("Failed to create white texture");
            return false;
        }

        // Camera constant buffer
        m_camera_buffer = uniform_buffer::create<camera_data>(m_device);
        if (!m_camera_buffer)
        {
            LUMINA_LOG_ERROR("Failed to create camera buffer");
            return false;
        }

        // Create default font from embedded TTF
        m_default_font = font_atlas::create(m_device, embedded_font_data, embedded_font_size, 16.0f);
        if (!m_default_font)
        {
            LUMINA_LOG_ERROR("Failed to create default font atlas");
            return false;
        }

        // ========================================================================
        // Create quad resources
        // ========================================================================

        // Quad vertex buffer
        size_t quad_vb_size = config.max_quads * vertices_per_quad * sizeof(quad_vertex);
        m_quad_vertex_buffer = vertex_buffer::create(m_device, nullptr, quad_vb_size, sizeof(quad_vertex), buffer_usage::dynamic);
        if (!m_quad_vertex_buffer)
        {
            LUMINA_LOG_ERROR("Failed to create quad vertex buffer");
            return false;
        }

        // Quad index buffer (static - precomputed)
        std::vector<uint32_t> quad_indices(config.max_quads * indices_per_quad);
        uint32_t offset = 0;
        for (uint32_t i = 0; i < config.max_quads; i++)
        {
            quad_indices[i * 6 + 0] = offset + 0;
            quad_indices[i * 6 + 1] = offset + 1;
            quad_indices[i * 6 + 2] = offset + 2;
            quad_indices[i * 6 + 3] = offset + 2;
            quad_indices[i * 6 + 4] = offset + 3;
            quad_indices[i * 6 + 5] = offset + 0;
            offset += 4;
        }
        m_quad_index_buffer = index_buffer::create(m_device, quad_indices.data(), quad_indices.size(), sizeof(uint32_t));
        if (!m_quad_index_buffer)
        {
            LUMINA_LOG_ERROR("Failed to create quad index buffer");
            return false;
        }

        // Quad shader
        {
            auto vs = get_quad_vs(m_device.get_api());
            auto ps = get_quad_ps(m_device.get_api());

            shader_desc desc;
            desc.vertex_blob = vs.data;
            desc.vertex_size = vs.size;
            desc.pixel_blob = ps.data;
            desc.pixel_size = ps.size;
            desc.vertex_entry = "VSMain";
            desc.pixel_entry = "PSMain";
            desc.debug_name = "Renderer2D Quad";

            m_quad_shader = shader::create(m_device, desc);
            if (!m_quad_shader)
            {
                LUMINA_LOG_ERROR("Failed to create quad shader");
                return false;
            }
        }

        // Quad input layout
        input_layout_desc quad_layout_desc;
        quad_layout_desc.add("POSITION", format::rgba32_float, vertex_semantic::position)
                        .add("COLOR", format::rgba32_float, vertex_semantic::color)
                        .add("TEXCOORD", format::rg32_float, vertex_semantic::texcoord)
                        .add("TEXINDEX", format::r32_float, vertex_semantic::custom)
                        .add("ZINDEX", format::r32_float, vertex_semantic::custom);

        m_quad_input_layout = input_layout::create(m_device, quad_layout_desc, m_quad_shader);
        if (!m_quad_input_layout)
        {
            LUMINA_LOG_ERROR("Failed to create quad input layout");
            return false;
        }

        // Quad binding layout (constant buffer + texture array + sampler)
        binding_layout_desc quad_binding_desc;
        quad_binding_desc.add_constant_buffer(0);     // Camera view-projection
        quad_binding_desc.add_texture_array(0, 32);   // Up to 32 textures per batch
        quad_binding_desc.add_sampler(0);

        m_quad_binding_layout = binding_layout::create(m_device, quad_binding_desc);
        if (!m_quad_binding_layout)
        {
            LUMINA_LOG_ERROR("Failed to create quad binding layout");
            return false;
        }

        // ========================================================================
        // Create circle resources
        // ========================================================================

        size_t circle_vb_size = config.max_circles * vertices_per_quad * sizeof(circle_vertex);
        m_circle_vertex_buffer = vertex_buffer::create(m_device, nullptr, circle_vb_size, sizeof(circle_vertex), buffer_usage::dynamic);
        if (!m_circle_vertex_buffer)
        {
            LUMINA_LOG_ERROR("Failed to create circle vertex buffer");
            return false;
        }

        // Reuse quad index buffer for circles
        m_circle_index_buffer = m_quad_index_buffer;

        // Circle shader
        {
            auto vs = get_circle_vs(m_device.get_api());
            auto ps = get_circle_ps(m_device.get_api());

            shader_desc desc;
            desc.vertex_blob = vs.data;
            desc.vertex_size = vs.size;
            desc.pixel_blob = ps.data;
            desc.pixel_size = ps.size;
            desc.vertex_entry = "VSMain";
            desc.pixel_entry = "PSMain";
            desc.debug_name = "Renderer2D Circle";

            m_circle_shader = shader::create(m_device, desc);
            if (!m_circle_shader)
            {
                LUMINA_LOG_ERROR("Failed to create circle shader");
                return false;
            }
        }

        // Circle input layout
        input_layout_desc circle_layout_desc;
        circle_layout_desc.add("POSITION", format::rgba32_float, vertex_semantic::position)    // world_position
                          .add("LOCALPOS", format::rgba32_float, vertex_semantic::custom)      // local_position
                          .add("COLOR", format::rgba32_float, vertex_semantic::color)
                          .add("TEXCOORD", format::rg32_float, vertex_semantic::texcoord)
                          .add("TEXINDEX", format::r32_float, vertex_semantic::custom)
                          .add("THICKNESS", format::r32_float, vertex_semantic::custom)
                          .add("FADE", format::r32_float, vertex_semantic::custom)
                          .add("ZINDEX", format::r32_float, vertex_semantic::custom);

        m_circle_input_layout = input_layout::create(m_device, circle_layout_desc, m_circle_shader);
        if (!m_circle_input_layout)
        {
            LUMINA_LOG_ERROR("Failed to create circle input layout");
            return false;
        }

        // Circle binding layout (same as quad)
        m_circle_binding_layout = m_quad_binding_layout;

        // ========================================================================
        // Create line resources
        // ========================================================================

        size_t line_vb_size = config.max_lines * 2 * sizeof(line_vertex);
        m_line_vertex_buffer = vertex_buffer::create(m_device, nullptr, line_vb_size, sizeof(line_vertex), buffer_usage::dynamic);
        if (!m_line_vertex_buffer)
        {
            LUMINA_LOG_ERROR("Failed to create line vertex buffer");
            return false;
        }

        // Line shader
        {
            auto vs = get_line_vs(m_device.get_api());
            auto ps = get_line_ps(m_device.get_api());

            shader_desc desc;
            desc.vertex_blob = vs.data;
            desc.vertex_size = vs.size;
            desc.pixel_blob = ps.data;
            desc.pixel_size = ps.size;
            desc.vertex_entry = "VSMain";
            desc.pixel_entry = "PSMain";
            desc.debug_name = "Renderer2D Line";

            m_line_shader = shader::create(m_device, desc);
            if (!m_line_shader)
            {
                LUMINA_LOG_ERROR("Failed to create line shader");
                return false;
            }
        }

        // Line input layout
        input_layout_desc line_layout_desc;
        line_layout_desc.add("POSITION", format::rgba32_float, vertex_semantic::position)
                        .add("COLOR", format::rgba32_float, vertex_semantic::color);

        m_line_input_layout = input_layout::create(m_device, line_layout_desc, m_line_shader);
        if (!m_line_input_layout)
        {
            LUMINA_LOG_ERROR("Failed to create line input layout");
            return false;
        }

        // Line binding layout (just camera constant buffer)
        binding_layout_desc line_binding_desc;
        line_binding_desc.add_constant_buffer(0);

        m_line_binding_layout = binding_layout::create(m_device, line_binding_desc);
        if (!m_line_binding_layout)
        {
            LUMINA_LOG_ERROR("Failed to create line binding layout");
            return false;
        }

        // ========================================================================
        // Create text resources
        // ========================================================================

        size_t text_vb_size = config.max_text_chars * vertices_per_quad * sizeof(text_vertex);
        m_text_vertex_buffer = vertex_buffer::create(m_device, nullptr, text_vb_size, sizeof(text_vertex), buffer_usage::dynamic);
        if (!m_text_vertex_buffer)
        {
            LUMINA_LOG_ERROR("Failed to create text vertex buffer");
            return false;
        }

        // Reuse quad index buffer for text
        m_text_index_buffer = m_quad_index_buffer;

        // Text shader
        {
            auto vs = get_text_vs(m_device.get_api());
            auto ps = get_text_ps(m_device.get_api());

            shader_desc desc;
            desc.vertex_blob = vs.data;
            desc.vertex_size = vs.size;
            desc.pixel_blob = ps.data;
            desc.pixel_size = ps.size;
            desc.vertex_entry = "VSMain";
            desc.pixel_entry = "PSMain";
            desc.debug_name = "Renderer2D Text";

            m_text_shader = shader::create(m_device, desc);
            if (!m_text_shader)
            {
                LUMINA_LOG_ERROR("Failed to create text shader");
                return false;
            }
        }

        // Text input layout (same structure as quad)
        m_text_input_layout = m_quad_input_layout;

        // Text binding layout (same as quad)
        m_text_binding_layout = m_quad_binding_layout;

        // ========================================================================
        // Create triangle resources
        // ========================================================================

        size_t triangle_vb_size = config.max_triangles * 3 * sizeof(triangle_vertex);
        m_triangle_vertex_buffer = vertex_buffer::create(m_device, nullptr, triangle_vb_size, sizeof(triangle_vertex), buffer_usage::dynamic);
        if (!m_triangle_vertex_buffer)
        {
            LUMINA_LOG_ERROR("Failed to create triangle vertex buffer");
            return false;
        }

        // Triangle shader
        {
            auto vs = get_triangle_vs(m_device.get_api());
            auto ps = get_triangle_ps(m_device.get_api());

            shader_desc desc;
            desc.vertex_blob = vs.data;
            desc.vertex_size = vs.size;
            desc.pixel_blob = ps.data;
            desc.pixel_size = ps.size;
            desc.vertex_entry = "VSMain";
            desc.pixel_entry = "PSMain";
            desc.debug_name = "Renderer2D Triangle";

            m_triangle_shader = shader::create(m_device, desc);
            if (!m_triangle_shader)
            {
                LUMINA_LOG_ERROR("Failed to create triangle shader");
                return false;
            }
        }

        // Triangle input layout (same structure as quad)
        m_triangle_input_layout = m_quad_input_layout;

        // Triangle binding layout (same as quad)
        m_triangle_binding_layout = m_quad_binding_layout;

        // ========================================================================
        // Create pixel resources
        // ========================================================================

        size_t pixel_vb_size = config.max_pixels * sizeof(pixel_vertex);
        m_pixel_vertex_buffer = vertex_buffer::create(m_device, nullptr, pixel_vb_size, sizeof(pixel_vertex), buffer_usage::dynamic);
        if (!m_pixel_vertex_buffer)
        {
            LUMINA_LOG_ERROR("Failed to create pixel vertex buffer");
            return false;
        }

        // Pixel shader
        {
            auto vs = get_pixel_vs(m_device.get_api());
            auto ps = get_pixel_ps(m_device.get_api());

            shader_desc desc;
            desc.vertex_blob = vs.data;
            desc.vertex_size = vs.size;
            desc.pixel_blob = ps.data;
            desc.pixel_size = ps.size;
            desc.vertex_entry = "VSMain";
            desc.pixel_entry = "PSMain";
            desc.debug_name = "Renderer2D Pixel";

            m_pixel_shader = shader::create(m_device, desc);
            if (!m_pixel_shader)
            {
                LUMINA_LOG_ERROR("Failed to create pixel shader");
                return false;
            }
        }

        // Pixel input layout
        input_layout_desc pixel_layout_desc;
        pixel_layout_desc.add("POSITION", format::rgba32_float, vertex_semantic::position)
                         .add("COLOR", format::rgba32_float, vertex_semantic::color)
                         .add("PSIZE", format::rgba32_float, vertex_semantic::custom);  // size + _pad[3]

        m_pixel_input_layout = input_layout::create(m_device, pixel_layout_desc, m_pixel_shader);
        if (!m_pixel_input_layout)
        {
            LUMINA_LOG_ERROR("Failed to create pixel input layout");
            return false;
        }

        // Pixel binding layout (just camera constant buffer)
        binding_layout_desc pixel_binding_desc;
        pixel_binding_desc.add_constant_buffer(0);

        m_pixel_binding_layout = binding_layout::create(m_device, pixel_binding_desc);
        if (!m_pixel_binding_layout)
        {
            LUMINA_LOG_ERROR("Failed to create pixel binding layout");
            return false;
        }

        // ========================================================================
        // Create grid resources
        // ========================================================================

        size_t grid_vb_size = config.max_grids * vertices_per_quad * sizeof(grid_vertex);
        m_grid_vertex_buffer = vertex_buffer::create(m_device, nullptr, grid_vb_size, sizeof(grid_vertex), buffer_usage::dynamic);
        if (!m_grid_vertex_buffer)
        {
            LUMINA_LOG_ERROR("Failed to create grid vertex buffer");
            return false;
        }

        // Reuse quad index buffer for grids
        m_grid_index_buffer = m_quad_index_buffer;

        // Grid shader
        {
            auto vs = get_grid_vs(m_device.get_api());
            auto ps = get_grid_ps(m_device.get_api());

            shader_desc desc;
            desc.vertex_blob = vs.data;
            desc.vertex_size = vs.size;
            desc.pixel_blob = ps.data;
            desc.pixel_size = ps.size;
            desc.vertex_entry = "VSMain";
            desc.pixel_entry = "PSMain";
            desc.debug_name = "Renderer2D Grid";

            m_grid_shader = shader::create(m_device, desc);
            if (!m_grid_shader)
            {
                LUMINA_LOG_ERROR("Failed to create grid shader");
                return false;
            }
        }

        // Grid input layout (complex - many per-vertex attributes)
        input_layout_desc grid_layout_desc;
        grid_layout_desc.add("POSITION", format::rgba32_float, vertex_semantic::position)
                        .add("LOCALPOS", format::rgba32_float, vertex_semantic::custom)
                        .add("LINECOLOR", format::rgba32_float, vertex_semantic::custom)
                        .add("GRIDSIZE", format::rg32_float, vertex_semantic::custom)
                        .add("CELLSIZE", format::r32_float, vertex_semantic::custom)
                        .add("LINEWIDTH", format::r32_float, vertex_semantic::custom)
                        .add("CHECKER", format::r32_float, vertex_semantic::custom)
                        .add("CHECKERCOLOR1", format::rgba32_float, vertex_semantic::custom)
                        .add("CHECKERCOLOR2", format::rgba32_float, vertex_semantic::custom);

        m_grid_input_layout = input_layout::create(m_device, grid_layout_desc, m_grid_shader);
        if (!m_grid_input_layout)
        {
            LUMINA_LOG_ERROR("Failed to create grid input layout");
            return false;
        }

        // Grid binding layout (just camera constant buffer)
        binding_layout_desc grid_binding_desc;
        grid_binding_desc.add_constant_buffer(0);

        m_grid_binding_layout = binding_layout::create(m_device, grid_binding_desc);
        if (!m_grid_binding_layout)
        {
            LUMINA_LOG_ERROR("Failed to create grid binding layout");
            return false;
        }

        // Pipelines will be created lazily based on render target format

        // Initialize lighting resources
        init_lighting_resources();

        m_initialized = true;

        LUMINA_LOG_INFO("Renderer2D initialized (quads: {}, circles: {}, lines: {}, text: {}, triangles: {}, pixels: {}, grids: {})",
                        config.max_quads, config.max_circles, config.max_lines,
                        config.max_text_chars, config.max_triangles, config.max_pixels, config.max_grids);
        return true;
    }

    void renderer2d::shutdown()
    {
        if (!m_initialized)
            return;

        // Shutdown lighting resources
        shutdown_lighting_resources();

        // Clear pipelines
        m_quad_pipeline.reset();
        m_circle_pipeline.reset();
        m_line_pipeline.reset();
        m_text_pipeline.reset();
        m_triangle_pipeline.reset();
        m_pixel_pipeline.reset();
        m_grid_pipeline.reset();

        // Clear binding layouts
        m_quad_binding_layout.reset();
        // Others share with quad

        // Clear input layouts
        m_quad_input_layout.reset();
        m_circle_input_layout.reset();
        m_line_input_layout.reset();
        m_pixel_input_layout.reset();
        m_grid_input_layout.reset();

        // Clear shaders
        m_quad_shader.reset();
        m_circle_shader.reset();
        m_line_shader.reset();
        m_text_shader.reset();
        m_triangle_shader.reset();
        m_pixel_shader.reset();
        m_grid_shader.reset();

        // Clear textures
        m_white_texture.reset();
        m_default_font.reset();
        m_current_sampler.reset();
        m_point_sampler.reset();
        m_default_sampler.reset();

        // Clear buffers
        m_quad_vertex_buffer.reset();
        m_quad_index_buffer.reset();
        m_circle_vertex_buffer.reset();
        m_line_vertex_buffer.reset();
        m_text_vertex_buffer.reset();
        m_triangle_vertex_buffer.reset();
        m_pixel_vertex_buffer.reset();
        m_grid_vertex_buffer.reset();

        // Clear layer data
        m_layers.clear();
        m_point_lights.clear();

        m_initialized = false;
    }

    void renderer2d::begin(const glm::mat4& projection)
    {
        begin(glm::mat4(1.0f), projection);
    }

    void renderer2d::begin(const glm::mat4& view, const glm::mat4& projection)
    {
        // Set up context with current frame's command list
        m_context->set_command_list(m_device.get_command_list());

        // Clear frame resources from previous frame (keep binding sets alive until now)
        m_frame_binding_sets.clear();

        // Reset vertex buffer offsets for new frame
        m_quad_vertex_offset = 0;
        m_circle_vertex_offset = 0;
        m_line_vertex_offset = 0;
        m_text_vertex_offset = 0;
        m_triangle_vertex_offset = 0;
        m_pixel_vertex_offset = 0;
        m_grid_vertex_offset = 0;

        // Auto-set default render target if none is currently set
        if (!m_current_target && !m_context->has_framebuffer())
        {
            set_default_render_target();
        }

        m_view_projection = projection * view;

        // Update camera constant buffer
        camera_data cam_data;
        cam_data.view_projection = m_view_projection;
        m_camera_buffer->update(cam_data, m_device.get_command_list());

        // If lighting is enabled, redirect rendering to the scene target
        if (m_lighting_enabled)
        {
            uint32_t width = m_current_target ? m_current_target->get_width() : m_device.get_width();
            uint32_t height = m_current_target ? m_current_target->get_height() : m_device.get_height();

            ensure_lighting_targets(width, height);

            // Render scene to the scene target
            m_context->set_render_target(m_scene_target);
            m_context->clear(clear_color(0.0f, 0.0f, 0.0f, 0.0f));
            m_context->set_viewport(0, 0, static_cast<float>(width), static_cast<float>(height));

            // Update format tracking for pipeline creation
            m_current_color_format = m_scene_target->get_color_format();
            m_current_depth_format = m_scene_target->get_depth_format();
        }

        start_batch();
    }

    void renderer2d::begin(const camera2d& camera)
    {
        begin(camera.get_view_matrix(), camera.get_projection_matrix());
    }

    void renderer2d::end()
    {
        flush_all();

        // If lighting is enabled, render lights and composite
        if (m_lighting_enabled)
        {
            flush_lights();
            composite_scene();
        }
    }

    void renderer2d::set_render_target(ref<render_target> target)
    {
        if (m_current_target != target)
        {
            flush_all();

            m_current_target = target;
            m_context->set_render_target(target);

            if (target)
            {
                m_current_color_format = target->get_color_format();
                m_current_depth_format = target->get_depth_format();

                // Set viewport to match render target size
                m_context->set_viewport(0, 0,
                    static_cast<float>(target->get_width()),
                    static_cast<float>(target->get_height()));
            }
        }
    }

    void renderer2d::set_default_render_target()
    {
        flush_all();

        m_current_target = nullptr;
        m_context->set_swapchain_framebuffer(m_device.get_current_framebuffer());
        m_context->set_viewport(0, 0, static_cast<float>(m_device.get_width()), static_cast<float>(m_device.get_height()));

        m_current_color_format = from_nvrhi_format(m_device.get_swapchain_format());
        m_current_depth_format = format::unknown;
    }

    void renderer2d::clear(const glm::vec4& color)
    {
        m_context->clear(clear_color(color.r, color.g, color.b, color.a));
    }

    void renderer2d::start_batch()
    {
        // Clear all layer batches
        for (auto& [layer_id, batch] : m_layers)
        {
            batch.clear();
            batch.texture_slots[0] = m_white_texture;
            batch.texture_slot_index = 1;
        }

        m_point_lights.clear();
    }

    renderer2d::layer_batch& renderer2d::get_layer(uint32_t layer_id)
    {
        auto it = m_layers.find(layer_id);
        if (it == m_layers.end())
        {
            // Create new layer batch
            auto& batch = m_layers[layer_id];
            batch.texture_slots[0] = m_white_texture;
            batch.texture_slot_index = 1;
            return batch;
        }
        return it->second;
    }

    float renderer2d::get_texture_index(uint32_t layer_id, ref<texture> tex)
    {
        if (!tex)
            return 0.0f;

        auto& batch = get_layer(layer_id);

        // Check if texture is already bound in this layer
        for (uint32_t i = 0; i < batch.texture_slot_index; i++)
        {
            if (batch.texture_slots[i] == tex)
                return static_cast<float>(i);
        }

        // Need to bind new texture
        if (batch.texture_slot_index >= m_config.max_textures)
        {
            // Out of texture slots for this layer, flush and reset texture slots
            // Note: flush_layer clears vertex data, but we must preserve blend modes
            // which were already set by the caller before calling get_texture_index
            blend_mode saved_quad_blend = batch.quad_blend;
            blend_mode saved_circle_blend = batch.circle_blend;
            blend_mode saved_triangle_blend = batch.triangle_blend;

            flush_layer(layer_id);

            // Reset only texture slots - vertex data was cleared by flush_layer
            batch.texture_slots.fill(nullptr);
            batch.texture_slots[0] = m_white_texture;
            batch.texture_slot_index = 1;

            // Restore blend modes (they may have been set before this call)
            batch.quad_blend = saved_quad_blend;
            batch.circle_blend = saved_circle_blend;
            batch.triangle_blend = saved_triangle_blend;
        }

        batch.texture_slots[batch.texture_slot_index] = tex;
        m_stats.texture_binds++;
        return static_cast<float>(batch.texture_slot_index++);
    }

    // ========================================================================
    // Drawing implementations
    // ========================================================================

    void renderer2d::draw_quad(const quad_desc& desc)
    {
        uint32_t layer_id = static_cast<uint32_t>(desc.layer);
        auto& batch = get_layer(layer_id);

        // Flush if blend mode changes - must flush lower layers first to maintain order
        if (batch.quad_count > 0 && batch.quad_blend != desc.blend)
        {
            flush_layers_up_to(layer_id);
            flush_quads(layer_id);
            // Note: flush_quads clears quad_vertices and quad_count at the end
        }
        batch.quad_blend = desc.blend;

        // Flush if batch is full - must flush lower layers first to maintain order
        if (batch.quad_count >= m_config.max_quads)
        {
            flush_layers_up_to(layer_id);
            flush_quads(layer_id);
            // Note: flush_quads clears quad_vertices and quad_count at the end
        }

        float tex_index = get_texture_index(layer_id, desc.texture);

        // Calculate corners based on rotation
        glm::vec2 size = desc.size;
        glm::vec2 origin = desc.origin * size;
        glm::vec3 pos = desc.position;

        glm::vec2 p0, p1, p2, p3;

        if (std::abs(desc.rotation) < 0.0001f)
        {
            // No rotation - simple case
            p0 = glm::vec2(pos) - origin;
            p1 = glm::vec2(pos) + glm::vec2(size.x - origin.x, -origin.y);
            p2 = glm::vec2(pos) + glm::vec2(size.x - origin.x, size.y - origin.y);
            p3 = glm::vec2(pos) + glm::vec2(-origin.x, size.y - origin.y);
        }
        else
        {
            // Rotated quad
            float cos_r = std::cos(desc.rotation);
            float sin_r = std::sin(desc.rotation);

            auto rotate = [&](const glm::vec2& offset) -> glm::vec2 {
                return glm::vec2(pos) + glm::vec2(
                    offset.x * cos_r - offset.y * sin_r,
                    offset.x * sin_r + offset.y * cos_r
                );
            };

            p0 = rotate(glm::vec2(-origin.x, -origin.y));
            p1 = rotate(glm::vec2(size.x - origin.x, -origin.y));
            p2 = rotate(glm::vec2(size.x - origin.x, size.y - origin.y));
            p3 = rotate(glm::vec2(-origin.x, size.y - origin.y));
        }

        // Store world positions - GPU will transform via camera buffer
        glm::vec4 world0 = glm::vec4(p0, pos.z, 1.0f);
        glm::vec4 world1 = glm::vec4(p1, pos.z, 1.0f);
        glm::vec4 world2 = glm::vec4(p2, pos.z, 1.0f);
        glm::vec4 world3 = glm::vec4(p3, pos.z, 1.0f);

        // Add vertices (CCW winding) with z_index from desc
        batch.quad_vertices.push_back({ world0, desc.color, desc.uv_min, tex_index, desc.z });
        batch.quad_vertices.push_back({ world1, desc.color, { desc.uv_max.x, desc.uv_min.y }, tex_index, desc.z });
        batch.quad_vertices.push_back({ world2, desc.color, desc.uv_max, tex_index, desc.z });
        batch.quad_vertices.push_back({ world3, desc.color, { desc.uv_min.x, desc.uv_max.y }, tex_index, desc.z });

        batch.quad_count++;
        m_stats.quad_count++;
    }

    void renderer2d::draw_circle(const circle_desc& desc)
    {
        uint32_t layer_id = static_cast<uint32_t>(desc.layer);
        auto& batch = get_layer(layer_id);

        // Flush if blend mode changes - must flush lower layers first to maintain order
        if (batch.circle_count > 0 && batch.circle_blend != desc.blend)
        {
            flush_layers_up_to(layer_id);
            flush_circles(layer_id);
            // Note: flush_circles clears circle_vertices and circle_count at the end
        }
        batch.circle_blend = desc.blend;

        // Flush if batch is full - must flush lower layers first to maintain order
        if (batch.circle_count >= m_config.max_circles)
        {
            flush_layers_up_to(layer_id);
            flush_circles(layer_id);
            // Note: flush_circles clears circle_vertices and circle_count at the end
        }

        float tex_index = get_texture_index(layer_id, desc.texture);

        // Circle is rendered as a quad with SDF in shader
        glm::vec2 radius = desc.radius;
        glm::vec3 pos = desc.position;

        // Quad corners
        glm::vec2 p0 = glm::vec2(pos) + glm::vec2(-radius.x, -radius.y);
        glm::vec2 p1 = glm::vec2(pos) + glm::vec2( radius.x, -radius.y);
        glm::vec2 p2 = glm::vec2(pos) + glm::vec2( radius.x,  radius.y);
        glm::vec2 p3 = glm::vec2(pos) + glm::vec2(-radius.x,  radius.y);

        // Store world positions - GPU will transform via camera buffer
        glm::vec4 world0 = glm::vec4(p0, pos.z, 1.0f);
        glm::vec4 world1 = glm::vec4(p1, pos.z, 1.0f);
        glm::vec4 world2 = glm::vec4(p2, pos.z, 1.0f);
        glm::vec4 world3 = glm::vec4(p3, pos.z, 1.0f);

        // Local coordinates for SDF (-1 to 1)
        glm::vec4 local0 = glm::vec4(-1.0f, -1.0f, 0.0f, 0.0f);
        glm::vec4 local1 = glm::vec4( 1.0f, -1.0f, 0.0f, 0.0f);
        glm::vec4 local2 = glm::vec4( 1.0f,  1.0f, 0.0f, 0.0f);
        glm::vec4 local3 = glm::vec4(-1.0f,  1.0f, 0.0f, 0.0f);

        // Add vertices with z_index from desc
        circle_vertex v0 = { world0, local0, desc.color, desc.uv_min, tex_index, desc.thickness, desc.fade, desc.z, {0, 0} };
        circle_vertex v1 = { world1, local1, desc.color, { desc.uv_max.x, desc.uv_min.y }, tex_index, desc.thickness, desc.fade, desc.z, {0, 0} };
        circle_vertex v2 = { world2, local2, desc.color, desc.uv_max, tex_index, desc.thickness, desc.fade, desc.z, {0, 0} };
        circle_vertex v3 = { world3, local3, desc.color, { desc.uv_min.x, desc.uv_max.y }, tex_index, desc.thickness, desc.fade, desc.z, {0, 0} };

        batch.circle_vertices.push_back(v0);
        batch.circle_vertices.push_back(v1);
        batch.circle_vertices.push_back(v2);
        batch.circle_vertices.push_back(v3);

        batch.circle_count++;
        m_stats.circle_count++;
    }

    void renderer2d::draw_line(const line_desc& desc)
    {
        uint32_t layer_id = static_cast<uint32_t>(desc.layer);
        auto& batch = get_layer(layer_id);

        // Flush if batch is full - must flush lower layers first to maintain order
        if (batch.line_count >= m_config.max_lines)
        {
            flush_layers_up_to(layer_id);
            flush_lines(layer_id);
            batch.line_vertices.clear();
            batch.line_count = 0;
        }

        if (desc.thickness <= 1.0f)
        {
            // Simple thin line - store world positions with z_index in w
            glm::vec4 world_start = glm::vec4(desc.start, desc.z);
            glm::vec4 world_end = glm::vec4(desc.end, desc.z);

            batch.line_vertices.push_back({ world_start, desc.color });
            batch.line_vertices.push_back({ world_end, desc.color });

            batch.line_count++;
            m_stats.line_count++;
        }
        else
        {
            // Thick line as quad
            glm::vec3 dir = glm::normalize(desc.end - desc.start);
            glm::vec3 normal = glm::vec3(-dir.y, dir.x, 0.0f) * (desc.thickness * 0.5f);

            glm::vec3 p0 = desc.start - normal;
            glm::vec3 p1 = desc.start + normal;
            glm::vec3 p2 = desc.end + normal;
            glm::vec3 p3 = desc.end - normal;

            draw_quad({
                .position = p0,
                .size = glm::vec2(glm::length(desc.end - desc.start), desc.thickness),
                .color = desc.color,
                .rotation = std::atan2(dir.y, dir.x),
                .origin = {0.0f, 0.5f},
                .layer = desc.layer,
                .z = desc.z
            });
        }
    }

    void renderer2d::draw_text(const text_desc& desc)
    {
        uint32_t layer_id = static_cast<uint32_t>(desc.layer);
        auto& batch = get_layer(layer_id);

        ref<font_atlas> font = desc.font ? desc.font : m_default_font;
        if (!font)
            return;

        ref<texture> font_tex = font->get_texture();
        float tex_index = get_texture_index(layer_id, font_tex);

        float scale = desc.scale;

        glm::vec2 text_size = font->measure_text(desc.text);
        float total_width = text_size.x * scale;
        float start_x = desc.position.x;

        switch (desc.alignment)
        {
            case text_alignment::center:
                start_x -= total_width * 0.5f;
                break;
            case text_alignment::right:
                start_x -= total_width;
                break;
            case text_alignment::left:
            default:
                break;
        }

        float x = start_x;
        float y = desc.position.y;
        float z = desc.position.z;

        for (char c : desc.text)
        {
            // Flush if batch is full - must flush lower layers first to maintain order
            if (batch.text_char_count >= m_config.max_text_chars)
            {
                flush_layers_up_to(layer_id);
                flush_text(layer_id);
                batch.text_vertices.clear();
                batch.text_char_count = 0;
                tex_index = get_texture_index(layer_id, font_tex);
            }

            const glyph_info* glyph = font->get_glyph(static_cast<uint8_t>(c));
            if (!glyph)
                continue;

            float x0 = x + glyph->x0 * scale;
            float y0 = y + glyph->y0 * scale;
            float x1 = x + glyph->x1 * scale;
            float y1 = y + glyph->y1 * scale;

            glm::vec2 p0 = glm::vec2(x0, y0);
            glm::vec2 p1 = glm::vec2(x1, y0);
            glm::vec2 p2 = glm::vec2(x1, y1);
            glm::vec2 p3 = glm::vec2(x0, y1);

            // Store world positions - GPU will transform via camera buffer
            glm::vec4 world0 = glm::vec4(p0, z, 1.0f);
            glm::vec4 world1 = glm::vec4(p1, z, 1.0f);
            glm::vec4 world2 = glm::vec4(p2, z, 1.0f);
            glm::vec4 world3 = glm::vec4(p3, z, 1.0f);

            batch.text_vertices.push_back({ world0, desc.color, { glyph->u0, glyph->v0 }, tex_index, desc.z });
            batch.text_vertices.push_back({ world1, desc.color, { glyph->u1, glyph->v0 }, tex_index, desc.z });
            batch.text_vertices.push_back({ world2, desc.color, { glyph->u1, glyph->v1 }, tex_index, desc.z });
            batch.text_vertices.push_back({ world3, desc.color, { glyph->u0, glyph->v1 }, tex_index, desc.z });

            batch.text_char_count++;
            m_stats.text_char_count++;

            x += glyph->advance_x * scale;
        }
    }

    void renderer2d::draw_triangle(const triangle_desc& desc)
    {
        uint32_t layer_id = static_cast<uint32_t>(desc.layer);
        auto& batch = get_layer(layer_id);

        // Flush if blend mode changes - must flush lower layers first to maintain order
        if (batch.triangle_count > 0 && batch.triangle_blend != desc.blend)
        {
            flush_layers_up_to(layer_id);
            flush_triangles(layer_id);
            // Note: flush_triangles clears triangle_vertices and triangle_count at the end
        }
        batch.triangle_blend = desc.blend;

        // Flush if batch is full - must flush lower layers first to maintain order
        if (batch.triangle_count >= m_config.max_triangles)
        {
            flush_layers_up_to(layer_id);
            flush_triangles(layer_id);
            // Note: flush_triangles clears triangle_vertices and triangle_count at the end
        }

        float tex_index = get_texture_index(layer_id, desc.texture);

        // Store world positions - GPU will transform via camera buffer
        glm::vec4 world0 = glm::vec4(desc.p0, 1.0f);
        glm::vec4 world1 = glm::vec4(desc.p1, 1.0f);
        glm::vec4 world2 = glm::vec4(desc.p2, 1.0f);

        // Add vertices with z_index from desc
        batch.triangle_vertices.push_back({ world0, desc.color, desc.uv0, tex_index, desc.z });
        batch.triangle_vertices.push_back({ world1, desc.color, desc.uv1, tex_index, desc.z });
        batch.triangle_vertices.push_back({ world2, desc.color, desc.uv2, tex_index, desc.z });

        batch.triangle_count++;
        m_stats.triangle_count++;
    }

    void renderer2d::draw_pixel(const pixel_desc& desc)
    {
        uint32_t layer_id = static_cast<uint32_t>(desc.layer);
        auto& batch = get_layer(layer_id);

        // Flush if batch is full - must flush lower layers first to maintain order
        if (batch.pixel_count >= m_config.max_pixels)
        {
            flush_layers_up_to(layer_id);
            flush_pixels(layer_id);
            batch.pixel_vertices.clear();
            batch.pixel_count = 0;
        }

        // Store world position with z_index in w
        glm::vec4 world_pos = glm::vec4(desc.position, desc.z);

        batch.pixel_vertices.push_back({ world_pos, desc.color, desc.size, {0, 0, 0} });

        batch.pixel_count++;
        m_stats.pixel_count++;
    }

    void renderer2d::draw_rect(const rect_desc& desc)
    {
        // Draw 4 lines forming a rectangle
        glm::vec3 p0 = desc.position;
        glm::vec3 p1 = desc.position + glm::vec3(desc.size.x, 0.0f, 0.0f);
        glm::vec3 p2 = desc.position + glm::vec3(desc.size.x, desc.size.y, 0.0f);
        glm::vec3 p3 = desc.position + glm::vec3(0.0f, desc.size.y, 0.0f);

        if (std::abs(desc.rotation) > 0.0001f)
        {
            // Rotated rectangle
            glm::vec2 center = glm::vec2(desc.position) + desc.size * 0.5f;
            float cos_r = std::cos(desc.rotation);
            float sin_r = std::sin(desc.rotation);

            auto rotate = [&](const glm::vec2& p) -> glm::vec3 {
                glm::vec2 offset = p - center;
                return glm::vec3(
                    center.x + offset.x * cos_r - offset.y * sin_r,
                    center.y + offset.x * sin_r + offset.y * cos_r,
                    desc.position.z
                );
            };

            p0 = rotate(glm::vec2(desc.position));
            p1 = rotate(glm::vec2(desc.position) + glm::vec2(desc.size.x, 0.0f));
            p2 = rotate(glm::vec2(desc.position) + desc.size);
            p3 = rotate(glm::vec2(desc.position) + glm::vec2(0.0f, desc.size.y));
        }

        draw_line({ .start = p0, .end = p1, .color = desc.color, .thickness = desc.thickness, .layer = desc.layer });
        draw_line({ .start = p1, .end = p2, .color = desc.color, .thickness = desc.thickness, .layer = desc.layer });
        draw_line({ .start = p2, .end = p3, .color = desc.color, .thickness = desc.thickness, .layer = desc.layer });
        draw_line({ .start = p3, .end = p0, .color = desc.color, .thickness = desc.thickness, .layer = desc.layer });
    }

    void renderer2d::draw_sprite(const texture_atlas& atlas, const std::string& region_name, const sprite_desc& desc)
    {
        const atlas_region* region = atlas.get_region(region_name);
        if (!region)
        {
            LUMINA_LOG_WARN("Sprite region '{}' not found in atlas", region_name);
            return;
        }

        draw_sprite(*region, atlas.get_texture(), desc);
    }

    void renderer2d::draw_sprite(const texture_atlas& atlas, uint32_t region_index, const sprite_desc& desc)
    {
        const atlas_region* region = atlas.get_region(region_index);
        if (!region)
        {
            LUMINA_LOG_WARN("Sprite region index {} not found in atlas", region_index);
            return;
        }

        draw_sprite(*region, atlas.get_texture(), desc);
    }

    void renderer2d::draw_sprite(const atlas_region& region, ref<texture> atlas_texture, const sprite_desc& desc)
    {
        // Determine size (use region size if not specified)
        glm::vec2 size = desc.size;
        if (size.x <= 0.0f || size.y <= 0.0f)
        {
            size = region.size;
        }

        // Handle UV flipping
        glm::vec2 uv_min = region.uv_min;
        glm::vec2 uv_max = region.uv_max;

        if (desc.flip_x)
        {
            std::swap(uv_min.x, uv_max.x);
        }
        if (desc.flip_y)
        {
            std::swap(uv_min.y, uv_max.y);
        }

        // Draw as a textured quad
        quad_desc quad;
        quad.position = desc.position;
        quad.size = size;
        quad.color = desc.color;
        quad.rotation = desc.rotation;
        quad.origin = desc.origin;
        quad.texture = atlas_texture;
        quad.uv_min = uv_min;
        quad.uv_max = uv_max;
        quad.layer = desc.layer;
        quad.z = desc.z;
        quad.blend = desc.blend;

        draw_quad(quad);
    }

    void renderer2d::draw_grid(const grid_desc& desc)
    {
        uint32_t layer_id = static_cast<uint32_t>(desc.layer);
        auto& batch = get_layer(layer_id);

        // Flush if batch is full - must flush lower layers first to maintain order
        if (batch.grid_count >= m_config.max_grids)
        {
            flush_layers_up_to(layer_id);
            flush_grids(layer_id);
            batch.grid_vertices.clear();
            batch.grid_count = 0;
        }

        // Grid is rendered as a quad with procedural pattern in shader
        glm::vec3 pos = desc.position;
        glm::vec2 size = desc.size;

        // Quad corners
        glm::vec2 p0 = glm::vec2(pos);
        glm::vec2 p1 = glm::vec2(pos) + glm::vec2(size.x, 0.0f);
        glm::vec2 p2 = glm::vec2(pos) + size;
        glm::vec2 p3 = glm::vec2(pos) + glm::vec2(0.0f, size.y);

        // Store world positions with z_index in w
        glm::vec4 world0 = glm::vec4(p0, pos.z, desc.z);
        glm::vec4 world1 = glm::vec4(p1, pos.z, desc.z);
        glm::vec4 world2 = glm::vec4(p2, pos.z, desc.z);
        glm::vec4 world3 = glm::vec4(p3, pos.z, desc.z);

        // Local positions (0 to size for grid calculation)
        glm::vec4 local0 = glm::vec4(0.0f, 0.0f, 0.0f, 0.0f);
        glm::vec4 local1 = glm::vec4(size.x, 0.0f, 0.0f, 0.0f);
        glm::vec4 local2 = glm::vec4(size.x, size.y, 0.0f, 0.0f);
        glm::vec4 local3 = glm::vec4(0.0f, size.y, 0.0f, 0.0f);

        float show_checker = desc.checkerboard ? 1.0f : 0.0f;

        // Add vertices (all vertices have same grid parameters)
        grid_vertex v0 = { world0, local0, desc.line_color, desc.size, desc.cell_size, desc.line_width, show_checker, desc.checker_color1, desc.checker_color2 };
        grid_vertex v1 = { world1, local1, desc.line_color, desc.size, desc.cell_size, desc.line_width, show_checker, desc.checker_color1, desc.checker_color2 };
        grid_vertex v2 = { world2, local2, desc.line_color, desc.size, desc.cell_size, desc.line_width, show_checker, desc.checker_color1, desc.checker_color2 };
        grid_vertex v3 = { world3, local3, desc.line_color, desc.size, desc.cell_size, desc.line_width, show_checker, desc.checker_color1, desc.checker_color2 };

        batch.grid_vertices.push_back(v0);
        batch.grid_vertices.push_back(v1);
        batch.grid_vertices.push_back(v2);
        batch.grid_vertices.push_back(v3);

        batch.grid_count++;
        m_stats.grid_count++;
    }

    // ========================================================================
    // Texture Filtering
    // ========================================================================

    void renderer2d::set_filter_mode(filter_mode mode)
    {
        if (m_filter_mode != mode)
        {
            m_filter_mode = mode;
            m_current_sampler = (mode == filter_mode::point) ? m_point_sampler : m_default_sampler;
        }
    }

    // ========================================================================
    // Lighting
    // ========================================================================

    void renderer2d::set_lighting_enabled(bool enabled)
    {
        m_lighting_enabled = enabled;
    }

    void renderer2d::set_ambient_light(const glm::vec3& color, float intensity)
    {
        m_ambient_color = color;
        m_ambient_intensity = intensity;
    }

    void renderer2d::draw_point_light(const point_light_desc& desc)
    {
        if (m_point_lights.size() >= m_config.max_point_lights)
        {
            LUMINA_LOG_WARN("Maximum point lights ({}) exceeded", m_config.max_point_lights);
            return;
        }

        point_light_data light;
        light.position = desc.position;
        light.intensity = desc.intensity;
        light.color = desc.color;
        light.radius = desc.radius;
        light.blend_mode = static_cast<float>(desc.blend);
        light.blend_alpha = desc.blend_alpha;
        light.attenuation = static_cast<float>(desc.attenuation);
        light.falloff = desc.falloff;

        m_point_lights.push_back(light);
        m_stats.point_light_count++;
    }

    // ========================================================================
    // Flush methods
    // ========================================================================

    void renderer2d::flush_all()
    {
        // Iterate layers in sorted order (std::map is ordered by key)
        for (auto& [layer_id, batch] : m_layers)
        {
            if (!batch.is_empty())
            {
                flush_layer(layer_id);
            }
        }
    }

    void renderer2d::flush_layer(uint32_t layer_id)
    {
        // Flush all primitive types for this layer in order
        flush_quads(layer_id);
        flush_circles(layer_id);
        flush_lines(layer_id);
        flush_text(layer_id);
        flush_triangles(layer_id);
        flush_pixels(layer_id);
        flush_grids(layer_id);
    }

    void renderer2d::flush_layers_up_to(uint32_t layer_id)
    {
        // Flush all layers with IDs less than the given layer_id
        // This ensures correct render order when a higher layer needs to flush early
        for (auto& [id, batch] : m_layers)
        {
            if (id >= layer_id)
                break;  // std::map is ordered, so we can stop early
            if (!batch.is_empty())
            {
                flush_layer(id);
            }
        }
    }

    void renderer2d::flush_quads(uint32_t layer_id)
    {
        auto it = m_layers.find(layer_id);
        if (it == m_layers.end())
            return;

        auto& batch = it->second;
        if (batch.quad_count == 0)
            return;

        // Get or create pipeline with correct blend mode (cached to keep alive)
        pipeline_desc desc;
        desc.shader_program = m_quad_shader;
        desc.vertex_layout = m_quad_input_layout;
        desc.binding_layouts.push_back(m_quad_binding_layout);
        desc.state.blend = batch.quad_blend;
        desc.state.depth = depth_mode::none;
        desc.state.cull = cull_mode::none;
        desc.state.primitive = topology::triangles;
        desc.color_format = m_current_color_format;
        desc.depth_format = m_current_depth_format;

        m_quad_pipeline = m_pipeline_cache->get_or_create(desc);
        if (!m_quad_pipeline)
        {
            LUMINA_LOG_ERROR("Failed to create quad pipeline");
            return;
        }

        // Check if we have room in the vertex buffer
        uint32_t vertices_needed = batch.quad_count * vertices_per_quad;
        if (m_quad_vertex_offset + vertices_needed > m_config.max_quads * vertices_per_quad)
        {
            // Buffer is full, reset offset (this may cause issues if GPU hasn't finished previous draws)
            // In practice, this shouldn't happen often with a large enough buffer
            LUMINA_LOG_WARN("Quad vertex buffer full, resetting offset (may cause visual artifacts)");
            m_quad_vertex_offset = 0;
        }

        // Calculate byte offset for vertex data
        size_t offset_bytes = m_quad_vertex_offset * sizeof(quad_vertex);

        // Update vertex buffer at current offset using command list for proper GPU synchronization
        m_quad_vertex_buffer->update_at_offset(batch.quad_vertices.data(), batch.quad_vertices.size() * sizeof(quad_vertex), offset_bytes, m_context->get_command_list());

        // Create binding set with camera buffer and all texture slots
        binding_set_desc bs_desc;
        bs_desc.layout = m_quad_binding_layout;
        bs_desc.add_constant_buffer(0, m_camera_buffer);

        // Bind all 32 texture slots (fill unused with white texture)
        for (uint32_t i = 0; i < 32; i++)
        {
            ref<texture> tex = batch.texture_slots[i] ? batch.texture_slots[i] : m_white_texture;
            bs_desc.add_texture_array_element(0, i, tex);
        }
        bs_desc.add_sampler(0, m_current_sampler);

        auto binding_set = binding_set::create(m_device, bs_desc);
        if (!binding_set)
        {
            LUMINA_LOG_ERROR("Failed to create quad binding set");
            return;
        }
        m_frame_binding_sets.push_back(binding_set);  // Keep alive until frame ends

        // Draw with base vertex offset to read from correct position in vertex buffer
        auto& ctx = *m_context;
        ctx.set_pipeline(m_quad_pipeline);
        ctx.set_binding_set(binding_set);
        ctx.set_vertex_buffer(m_quad_vertex_buffer);
        ctx.set_index_buffer(m_quad_index_buffer);
        ctx.draw_indexed(batch.quad_count * indices_per_quad, 0, static_cast<int32_t>(m_quad_vertex_offset));

        m_stats.draw_calls++;

        // Advance vertex offset for next flush
        m_quad_vertex_offset += batch.quad_count * vertices_per_quad;

        batch.quad_vertices.clear();
        batch.quad_count = 0;

        // Reset texture slots after flush so next batch starts fresh
        batch.texture_slots.fill(nullptr);
        batch.texture_slots[0] = m_white_texture;
        batch.texture_slot_index = 1;
    }

    void renderer2d::flush_circles(uint32_t layer_id)
    {
        auto it = m_layers.find(layer_id);
        if (it == m_layers.end())
            return;

        auto& batch = it->second;
        if (batch.circle_count == 0)
            return;

        // Ensure pipeline exists with correct blend mode
        if (!m_circle_pipeline ||
            m_circle_pipeline->get_desc().color_format != m_current_color_format ||
            m_circle_pipeline->get_desc().depth_format != m_current_depth_format ||
            m_circle_pipeline->get_desc().state.blend != batch.circle_blend)
        {
            pipeline_desc desc;
            desc.shader_program = m_circle_shader;
            desc.vertex_layout = m_circle_input_layout;
            desc.binding_layouts.push_back(m_circle_binding_layout);
            desc.state.blend = batch.circle_blend;
            desc.state.depth = depth_mode::none;
            desc.state.cull = cull_mode::none;
            desc.state.primitive = topology::triangles;
            desc.color_format = m_current_color_format;
            desc.depth_format = m_current_depth_format;

            m_circle_pipeline = m_pipeline_cache->get_or_create(desc);
            if (!m_circle_pipeline)
            {
                LUMINA_LOG_ERROR("Failed to create circle pipeline");
                return;
            }
        }

        // Check if we have room in the vertex buffer
        uint32_t vertices_needed = batch.circle_count * vertices_per_quad;
        if (m_circle_vertex_offset + vertices_needed > m_config.max_circles * vertices_per_quad)
        {
            LUMINA_LOG_WARN("Circle vertex buffer full, resetting offset");
            m_circle_vertex_offset = 0;
        }

        // Calculate byte offset and update vertex buffer at current offset
        size_t offset_bytes = m_circle_vertex_offset * sizeof(circle_vertex);
        m_circle_vertex_buffer->update_at_offset(batch.circle_vertices.data(), batch.circle_vertices.size() * sizeof(circle_vertex), offset_bytes, m_context->get_command_list());

        // Create binding set with camera buffer and all texture slots
        binding_set_desc bs_desc;
        bs_desc.layout = m_circle_binding_layout;
        bs_desc.add_constant_buffer(0, m_camera_buffer);

        // Bind all 32 texture slots (fill unused with white texture)
        for (uint32_t i = 0; i < 32; i++)
        {
            ref<texture> tex = batch.texture_slots[i] ? batch.texture_slots[i] : m_white_texture;
            bs_desc.add_texture_array_element(0, i, tex);
        }
        bs_desc.add_sampler(0, m_current_sampler);

        auto binding_set = binding_set::create(m_device, bs_desc);
        if (!binding_set)
        {
            LUMINA_LOG_ERROR("Failed to create circle binding set");
            return;
        }
        m_frame_binding_sets.push_back(binding_set);  // Keep alive until frame ends

        // Draw with base vertex offset
        auto& ctx = *m_context;
        ctx.set_pipeline(m_circle_pipeline);
        ctx.set_binding_set(binding_set);
        ctx.set_vertex_buffer(m_circle_vertex_buffer);
        ctx.set_index_buffer(m_circle_index_buffer);
        ctx.draw_indexed(batch.circle_count * indices_per_quad, 0, static_cast<int32_t>(m_circle_vertex_offset));

        m_stats.draw_calls++;

        // Advance vertex offset for next flush
        m_circle_vertex_offset += batch.circle_count * vertices_per_quad;

        batch.circle_vertices.clear();
        batch.circle_count = 0;
    }

    void renderer2d::flush_lines(uint32_t layer_id)
    {
        auto it = m_layers.find(layer_id);
        if (it == m_layers.end())
            return;

        auto& batch = it->second;
        if (batch.line_count == 0)
            return;

        // Ensure pipeline exists
        if (!m_line_pipeline ||
            m_line_pipeline->get_desc().color_format != m_current_color_format ||
            m_line_pipeline->get_desc().depth_format != m_current_depth_format)
        {
            pipeline_desc desc;
            desc.shader_program = m_line_shader;
            desc.vertex_layout = m_line_input_layout;
            desc.binding_layouts.push_back(m_line_binding_layout);
            desc.state.blend = blend_mode::alpha;
            desc.state.depth = depth_mode::none;
            desc.state.cull = cull_mode::none;
            desc.state.primitive = topology::lines;
            desc.color_format = m_current_color_format;
            desc.depth_format = m_current_depth_format;

            m_line_pipeline = m_pipeline_cache->get_or_create(desc);
            if (!m_line_pipeline)
            {
                LUMINA_LOG_ERROR("Failed to create line pipeline");
                return;
            }
        }

        // Check if we have room in the vertex buffer (2 vertices per line)
        uint32_t vertices_needed = batch.line_count * 2;
        if (m_line_vertex_offset + vertices_needed > m_config.max_lines * 2)
        {
            LUMINA_LOG_WARN("Line vertex buffer full, resetting offset");
            m_line_vertex_offset = 0;
        }

        // Calculate byte offset and update vertex buffer at current offset
        size_t offset_bytes = m_line_vertex_offset * sizeof(line_vertex);
        m_line_vertex_buffer->update_at_offset(batch.line_vertices.data(), batch.line_vertices.size() * sizeof(line_vertex), offset_bytes, m_context->get_command_list());

        // Create binding set with camera buffer
        binding_set_desc bs_desc;
        bs_desc.layout = m_line_binding_layout;
        bs_desc.add_constant_buffer(0, m_camera_buffer);

        auto binding_set = binding_set::create(m_device, bs_desc);
        if (!binding_set)
        {
            LUMINA_LOG_ERROR("Failed to create line binding set");
            return;
        }
        m_frame_binding_sets.push_back(binding_set);  // Keep alive until frame ends

        // Draw with start vertex offset (lines don't use index buffer)
        auto& ctx = *m_context;
        ctx.set_pipeline(m_line_pipeline);
        ctx.set_binding_set(binding_set);
        ctx.set_vertex_buffer(m_line_vertex_buffer);
        ctx.draw(batch.line_count * 2, m_line_vertex_offset);

        m_stats.draw_calls++;

        // Advance vertex offset for next flush
        m_line_vertex_offset += batch.line_count * 2;

        batch.line_vertices.clear();
        batch.line_count = 0;
    }

    void renderer2d::flush_text(uint32_t layer_id)
    {
        auto it = m_layers.find(layer_id);
        if (it == m_layers.end())
            return;

        auto& batch = it->second;
        if (batch.text_char_count == 0)
            return;

        // Ensure pipeline exists
        if (!m_text_pipeline ||
            m_text_pipeline->get_desc().color_format != m_current_color_format ||
            m_text_pipeline->get_desc().depth_format != m_current_depth_format)
        {
            pipeline_desc desc;
            desc.shader_program = m_text_shader;
            desc.vertex_layout = m_text_input_layout;
            desc.binding_layouts.push_back(m_text_binding_layout);
            desc.state.blend = blend_mode::alpha;
            desc.state.depth = depth_mode::none;
            desc.state.cull = cull_mode::none;
            desc.state.primitive = topology::triangles;
            desc.color_format = m_current_color_format;
            desc.depth_format = m_current_depth_format;

            m_text_pipeline = m_pipeline_cache->get_or_create(desc);
            if (!m_text_pipeline)
            {
                LUMINA_LOG_ERROR("Failed to create text pipeline");
                return;
            }
        }

        // Check if we have room in the vertex buffer (4 vertices per character)
        uint32_t vertices_needed = batch.text_char_count * vertices_per_quad;
        if (m_text_vertex_offset + vertices_needed > m_config.max_text_chars * vertices_per_quad)
        {
            LUMINA_LOG_WARN("Text vertex buffer full, resetting offset");
            m_text_vertex_offset = 0;
        }

        // Calculate byte offset and update vertex buffer at current offset
        size_t offset_bytes = m_text_vertex_offset * sizeof(text_vertex);
        m_text_vertex_buffer->update_at_offset(batch.text_vertices.data(), batch.text_vertices.size() * sizeof(text_vertex), offset_bytes, m_context->get_command_list());

        // Create binding set with camera buffer and all texture slots
        binding_set_desc bs_desc;
        bs_desc.layout = m_text_binding_layout;
        bs_desc.add_constant_buffer(0, m_camera_buffer);

        // Bind all 32 texture slots (fill unused with white texture)
        for (uint32_t i = 0; i < 32; i++)
        {
            ref<texture> tex = batch.texture_slots[i] ? batch.texture_slots[i] : m_white_texture;
            bs_desc.add_texture_array_element(0, i, tex);
        }
        bs_desc.add_sampler(0, m_current_sampler);

        auto binding_set = binding_set::create(m_device, bs_desc);
        if (!binding_set)
        {
            LUMINA_LOG_ERROR("Failed to create text binding set");
            return;
        }
        m_frame_binding_sets.push_back(binding_set);  // Keep alive until frame ends

        // Draw with base vertex offset
        auto& ctx = *m_context;
        ctx.set_pipeline(m_text_pipeline);
        ctx.set_binding_set(binding_set);
        ctx.set_vertex_buffer(m_text_vertex_buffer);
        ctx.set_index_buffer(m_text_index_buffer);
        ctx.draw_indexed(batch.text_char_count * indices_per_quad, 0, static_cast<int32_t>(m_text_vertex_offset));

        m_stats.draw_calls++;

        // Advance vertex offset for next flush
        m_text_vertex_offset += batch.text_char_count * vertices_per_quad;

        batch.text_vertices.clear();
        batch.text_char_count = 0;
    }

    void renderer2d::flush_triangles(uint32_t layer_id)
    {
        auto it = m_layers.find(layer_id);
        if (it == m_layers.end())
            return;

        auto& batch = it->second;
        if (batch.triangle_count == 0)
            return;

        // Ensure pipeline exists with correct blend mode
        if (!m_triangle_pipeline ||
            m_triangle_pipeline->get_desc().color_format != m_current_color_format ||
            m_triangle_pipeline->get_desc().depth_format != m_current_depth_format ||
            m_triangle_pipeline->get_desc().state.blend != batch.triangle_blend)
        {
            pipeline_desc desc;
            desc.shader_program = m_triangle_shader;
            desc.vertex_layout = m_triangle_input_layout;
            desc.binding_layouts.push_back(m_triangle_binding_layout);
            desc.state.blend = batch.triangle_blend;
            desc.state.depth = depth_mode::none;
            desc.state.cull = cull_mode::none;
            desc.state.primitive = topology::triangles;
            desc.color_format = m_current_color_format;
            desc.depth_format = m_current_depth_format;

            m_triangle_pipeline = m_pipeline_cache->get_or_create(desc);
            if (!m_triangle_pipeline)
            {
                LUMINA_LOG_ERROR("Failed to create triangle pipeline");
                return;
            }
        }

        // Check if we have room in the vertex buffer (3 vertices per triangle)
        uint32_t vertices_needed = batch.triangle_count * 3;
        if (m_triangle_vertex_offset + vertices_needed > m_config.max_triangles * 3)
        {
            LUMINA_LOG_WARN("Triangle vertex buffer full, resetting offset");
            m_triangle_vertex_offset = 0;
        }

        // Calculate byte offset and update vertex buffer at current offset
        size_t offset_bytes = m_triangle_vertex_offset * sizeof(triangle_vertex);
        m_triangle_vertex_buffer->update_at_offset(batch.triangle_vertices.data(), batch.triangle_vertices.size() * sizeof(triangle_vertex), offset_bytes, m_context->get_command_list());

        // Create binding set with camera buffer and all texture slots
        binding_set_desc bs_desc;
        bs_desc.layout = m_triangle_binding_layout;
        bs_desc.add_constant_buffer(0, m_camera_buffer);

        // Bind all 32 texture slots (fill unused with white texture)
        for (uint32_t i = 0; i < 32; i++)
        {
            ref<texture> tex = batch.texture_slots[i] ? batch.texture_slots[i] : m_white_texture;
            bs_desc.add_texture_array_element(0, i, tex);
        }
        bs_desc.add_sampler(0, m_current_sampler);

        auto binding_set = binding_set::create(m_device, bs_desc);
        if (!binding_set)
        {
            LUMINA_LOG_ERROR("Failed to create triangle binding set");
            return;
        }
        m_frame_binding_sets.push_back(binding_set);  // Keep alive until frame ends

        // Draw with start vertex offset (no index buffer - raw triangles)
        auto& ctx = *m_context;
        ctx.set_pipeline(m_triangle_pipeline);
        ctx.set_binding_set(binding_set);
        ctx.set_vertex_buffer(m_triangle_vertex_buffer);
        ctx.draw(batch.triangle_count * 3, m_triangle_vertex_offset);

        m_stats.draw_calls++;

        // Advance vertex offset for next flush
        m_triangle_vertex_offset += batch.triangle_count * 3;

        batch.triangle_vertices.clear();
        batch.triangle_count = 0;
    }

    void renderer2d::flush_pixels(uint32_t layer_id)
    {
        auto it = m_layers.find(layer_id);
        if (it == m_layers.end())
            return;

        auto& batch = it->second;
        if (batch.pixel_count == 0)
            return;

        // Ensure pipeline exists
        if (!m_pixel_pipeline ||
            m_pixel_pipeline->get_desc().color_format != m_current_color_format ||
            m_pixel_pipeline->get_desc().depth_format != m_current_depth_format)
        {
            pipeline_desc desc;
            desc.shader_program = m_pixel_shader;
            desc.vertex_layout = m_pixel_input_layout;
            desc.binding_layouts.push_back(m_pixel_binding_layout);
            desc.state.blend = blend_mode::alpha;
            desc.state.depth = depth_mode::none;
            desc.state.cull = cull_mode::none;
            desc.state.primitive = topology::points;
            desc.color_format = m_current_color_format;
            desc.depth_format = m_current_depth_format;

            m_pixel_pipeline = m_pipeline_cache->get_or_create(desc);
            if (!m_pixel_pipeline)
            {
                LUMINA_LOG_ERROR("Failed to create pixel pipeline");
                return;
            }
        }

        // Check if we have room in the vertex buffer
        uint32_t max_vertices = m_config.max_pixels;
        if (m_pixel_vertex_offset + batch.pixel_count > max_vertices)
        {
            LUMINA_LOG_WARN("Pixel vertex buffer full, resetting offset (may cause visual artifacts)");
            m_pixel_vertex_offset = 0;
        }

        // Update vertex buffer at current offset
        size_t byte_offset = m_pixel_vertex_offset * sizeof(pixel_vertex);
        m_pixel_vertex_buffer->update_at_offset(batch.pixel_vertices.data(), batch.pixel_vertices.size() * sizeof(pixel_vertex), byte_offset, m_context->get_command_list());

        // Create binding set with camera buffer
        binding_set_desc bs_desc;
        bs_desc.layout = m_pixel_binding_layout;
        bs_desc.add_constant_buffer(0, m_camera_buffer);

        auto binding_set = binding_set::create(m_device, bs_desc);
        if (!binding_set)
        {
            LUMINA_LOG_ERROR("Failed to create pixel binding set");
            return;
        }
        m_frame_binding_sets.push_back(binding_set);  // Keep alive until frame ends

        // Draw with start_vertex offset
        auto& ctx = *m_context;
        ctx.set_pipeline(m_pixel_pipeline);
        ctx.set_binding_set(binding_set);
        ctx.set_vertex_buffer(m_pixel_vertex_buffer);
        ctx.draw(batch.pixel_count, m_pixel_vertex_offset);

        m_stats.draw_calls++;

        // Advance vertex offset for next flush
        m_pixel_vertex_offset += batch.pixel_count;

        batch.pixel_vertices.clear();
        batch.pixel_count = 0;
    }

    void renderer2d::flush_grids(uint32_t layer_id)
    {
        auto it = m_layers.find(layer_id);
        if (it == m_layers.end())
            return;

        auto& batch = it->second;
        if (batch.grid_count == 0)
            return;

        // Ensure pipeline exists
        if (!m_grid_pipeline ||
            m_grid_pipeline->get_desc().color_format != m_current_color_format ||
            m_grid_pipeline->get_desc().depth_format != m_current_depth_format)
        {
            pipeline_desc desc;
            desc.shader_program = m_grid_shader;
            desc.vertex_layout = m_grid_input_layout;
            desc.binding_layouts.push_back(m_grid_binding_layout);
            desc.state.blend = blend_mode::alpha;
            desc.state.depth = depth_mode::none;
            desc.state.cull = cull_mode::none;
            desc.state.primitive = topology::triangles;
            desc.color_format = m_current_color_format;
            desc.depth_format = m_current_depth_format;

            m_grid_pipeline = m_pipeline_cache->get_or_create(desc);
            if (!m_grid_pipeline)
            {
                LUMINA_LOG_ERROR("Failed to create grid pipeline");
                return;
            }
        }

        // Check if we have room in the vertex buffer
        uint32_t vertices_needed = batch.grid_count * vertices_per_quad;
        uint32_t max_vertices = m_config.max_grids * vertices_per_quad;
        if (m_grid_vertex_offset + vertices_needed > max_vertices)
        {
            LUMINA_LOG_WARN("Grid vertex buffer full, resetting offset (may cause visual artifacts)");
            m_grid_vertex_offset = 0;
        }

        // Update vertex buffer at current offset
        size_t byte_offset = m_grid_vertex_offset * sizeof(grid_vertex);
        m_grid_vertex_buffer->update_at_offset(batch.grid_vertices.data(), batch.grid_vertices.size() * sizeof(grid_vertex), byte_offset, m_context->get_command_list());

        // Create binding set with camera buffer
        binding_set_desc bs_desc;
        bs_desc.layout = m_grid_binding_layout;
        bs_desc.add_constant_buffer(0, m_camera_buffer);

        auto binding_set = binding_set::create(m_device, bs_desc);
        if (!binding_set)
        {
            LUMINA_LOG_ERROR("Failed to create grid binding set");
            return;
        }
        m_frame_binding_sets.push_back(binding_set);  // Keep alive until frame ends

        // Draw with base_vertex offset for indexed drawing
        auto& ctx = *m_context;
        ctx.set_pipeline(m_grid_pipeline);
        ctx.set_binding_set(binding_set);
        ctx.set_vertex_buffer(m_grid_vertex_buffer);
        ctx.set_index_buffer(m_grid_index_buffer);
        ctx.draw_indexed(batch.grid_count * indices_per_quad, 0, m_grid_vertex_offset);

        m_stats.draw_calls++;

        // Advance vertex offset for next flush
        m_grid_vertex_offset += vertices_needed;

        batch.grid_vertices.clear();
        batch.grid_count = 0;
    }

    // ========================================================================
    // Lighting Implementation
    // ========================================================================

    void renderer2d::init_lighting_resources()
    {
        // Create fullscreen quad vertex buffer (NDC coordinates)
        fullscreen_vertex fullscreen_verts[4] = {
            {{ -1.0f, -1.0f, 0.0f, 1.0f }, { 0.0f, 1.0f }},  // Bottom-left
            {{  1.0f, -1.0f, 0.0f, 1.0f }, { 1.0f, 1.0f }},  // Bottom-right
            {{  1.0f,  1.0f, 0.0f, 1.0f }, { 1.0f, 0.0f }},  // Top-right
            {{ -1.0f,  1.0f, 0.0f, 1.0f }, { 0.0f, 0.0f }},  // Top-left
        };

        m_fullscreen_vertex_buffer = vertex_buffer::create(m_device, fullscreen_verts, sizeof(fullscreen_verts), sizeof(fullscreen_vertex), buffer_usage::immutable);
        if (!m_fullscreen_vertex_buffer)
        {
            LUMINA_LOG_ERROR("Failed to create fullscreen vertex buffer");
            return;
        }

        // Point light shader
        {
            auto vs = get_point_light_vs(m_device.get_api());
            auto ps = get_point_light_ps(m_device.get_api());

            shader_desc desc;
            desc.vertex_blob = vs.data;
            desc.vertex_size = vs.size;
            desc.pixel_blob = ps.data;
            desc.pixel_size = ps.size;
            desc.vertex_entry = "VSMain";
            desc.pixel_entry = "PSMain";
            desc.debug_name = "Point Light";

            m_point_light_shader = shader::create(m_device, desc);
            if (!m_point_light_shader)
            {
                LUMINA_LOG_ERROR("Failed to create point light shader");
                return;
            }
        }

        // Point light input layout
        input_layout_desc light_layout_desc;
        light_layout_desc.add("POSITION", format::rgba32_float, vertex_semantic::position)
                         .add("TEXCOORD", format::rg32_float, vertex_semantic::texcoord);

        m_point_light_input_layout = input_layout::create(m_device, light_layout_desc, m_point_light_shader);
        if (!m_point_light_input_layout)
        {
            LUMINA_LOG_ERROR("Failed to create point light input layout");
            return;
        }

        // Point light binding layout (constant buffer only)
        binding_layout_desc light_binding_desc;
        light_binding_desc.add_constant_buffer(0);

        m_point_light_binding_layout = binding_layout::create(m_device, light_binding_desc);
        if (!m_point_light_binding_layout)
        {
            LUMINA_LOG_ERROR("Failed to create point light binding layout");
            return;
        }

        // Point light constant buffer
        // Structure: float2 position, float2 viewport_size, float3 color, float intensity,
        //            float radius, float attenuation, float falloff, float pad, mat4 inv_view_proj
        m_light_params_buffer = uniform_buffer::create(m_device, 128); // Generous size for alignment
        if (!m_light_params_buffer)
        {
            LUMINA_LOG_ERROR("Failed to create light params buffer");
            return;
        }

        // Composite shader
        {
            auto vs = get_composite_vs(m_device.get_api());
            auto ps = get_composite_ps(m_device.get_api());

            shader_desc desc;
            desc.vertex_blob = vs.data;
            desc.vertex_size = vs.size;
            desc.pixel_blob = ps.data;
            desc.pixel_size = ps.size;
            desc.vertex_entry = "VSMain";
            desc.pixel_entry = "PSMain";
            desc.debug_name = "Composite";

            m_composite_shader = shader::create(m_device, desc);
            if (!m_composite_shader)
            {
                LUMINA_LOG_ERROR("Failed to create composite shader");
                return;
            }
        }

        // Composite input layout (same as point light)
        m_composite_input_layout = m_point_light_input_layout;

        // Composite binding layout (constant buffer + 2 textures + sampler)
        binding_layout_desc composite_binding_desc;
        composite_binding_desc.add_constant_buffer(0);
        composite_binding_desc.add_texture(0);  // Scene texture
        composite_binding_desc.add_texture(1);  // Light texture
        composite_binding_desc.add_sampler(0);

        m_composite_binding_layout = binding_layout::create(m_device, composite_binding_desc);
        if (!m_composite_binding_layout)
        {
            LUMINA_LOG_ERROR("Failed to create composite binding layout");
            return;
        }

        // Composite constant buffer
        // Structure: float3 ambient_color, float ambient_intensity
        m_composite_params_buffer = uniform_buffer::create(m_device, 32);
        if (!m_composite_params_buffer)
        {
            LUMINA_LOG_ERROR("Failed to create composite params buffer");
            return;
        }

        LUMINA_LOG_INFO("Lighting resources initialized");
    }

    void renderer2d::shutdown_lighting_resources()
    {
        m_scene_target.reset();
        m_light_accumulation.reset();
        m_fullscreen_vertex_buffer.reset();
        m_point_light_shader.reset();
        m_point_light_input_layout.reset();
        m_point_light_binding_layout.reset();
        m_point_light_pipeline.reset();
        m_composite_shader.reset();
        m_composite_input_layout.reset();
        m_composite_binding_layout.reset();
        m_composite_pipeline.reset();
        m_light_params_buffer.reset();
        m_composite_params_buffer.reset();

        m_lighting_target_width = 0;
        m_lighting_target_height = 0;
    }

    void renderer2d::ensure_lighting_targets(uint32_t width, uint32_t height)
    {
        if (m_lighting_target_width == width && m_lighting_target_height == height)
            return;

        // Create or resize scene target
        if (!m_scene_target || m_scene_target->get_width() != width || m_scene_target->get_height() != height)
        {
            m_scene_target = render_target::create(m_device, width, height, format::rgba16_float);
            if (!m_scene_target)
            {
                LUMINA_LOG_ERROR("Failed to create scene render target for lighting");
                return;
            }
        }

        // Create or resize light accumulation target
        if (!m_light_accumulation || m_light_accumulation->get_width() != width || m_light_accumulation->get_height() != height)
        {
            m_light_accumulation = render_target::create(m_device, width, height, format::rgba16_float);
            if (!m_light_accumulation)
            {
                LUMINA_LOG_ERROR("Failed to create light accumulation render target");
                return;
            }
        }

        m_lighting_target_width = width;
        m_lighting_target_height = height;

        LUMINA_LOG_INFO("Lighting targets resized to {}x{}", width, height);
    }

    void renderer2d::flush_lights()
    {
        if (m_point_lights.empty())
            return;

        // Ensure point light pipeline exists
        if (!m_point_light_pipeline)
        {
            pipeline_desc desc;
            desc.shader_program = m_point_light_shader;
            desc.vertex_layout = m_point_light_input_layout;
            desc.binding_layouts.push_back(m_point_light_binding_layout);
            desc.state.blend = blend_mode::additive;  // Additive blending for light accumulation
            desc.state.depth = depth_mode::none;
            desc.state.cull = cull_mode::none;
            desc.state.primitive = topology::triangles;
            desc.color_format = m_light_accumulation ? m_light_accumulation->get_color_format() : format::rgba16_float;
            desc.depth_format = format::unknown;

            m_point_light_pipeline = m_pipeline_cache->get_or_create(desc);
            if (!m_point_light_pipeline)
            {
                LUMINA_LOG_ERROR("Failed to create point light pipeline");
                return;
            }
        }

        // Clear light accumulation buffer
        m_context->set_render_target(m_light_accumulation);
        m_context->clear(clear_color(0.0f, 0.0f, 0.0f, 0.0f));

        // Calculate inverse view-projection matrix
        glm::mat4 inv_view_proj = glm::inverse(m_view_projection);

        // Render each point light
        for (const auto& light : m_point_lights)
        {
            // Light params structure (must match HLSL cbuffer layout)
            struct alignas(16) light_params
            {
                glm::vec2 position;
                glm::vec2 viewport_size;
                glm::vec3 color;
                float intensity;
                float radius;
                float attenuation_model;
                float falloff;
                float _pad;
                glm::mat4 inv_view_proj;
            };

            light_params params;
            params.position = glm::vec2(light.position.x, light.position.y);
            params.viewport_size = glm::vec2(static_cast<float>(m_lighting_target_width), static_cast<float>(m_lighting_target_height));
            params.color = light.color;
            params.intensity = light.intensity;
            params.radius = light.radius;
            params.attenuation_model = light.attenuation;
            params.falloff = light.falloff;
            params._pad = 0.0f;
            params.inv_view_proj = inv_view_proj;

            // Update constant buffer
            m_light_params_buffer->update(params, m_device.get_command_list());

            // Create binding set for this light
            binding_set_desc bs_desc;
            bs_desc.layout = m_point_light_binding_layout;
            bs_desc.add_constant_buffer(0, m_light_params_buffer);

            auto binding_set = binding_set::create(m_device, bs_desc);
            if (!binding_set)
            {
                LUMINA_LOG_ERROR("Failed to create point light binding set");
                continue;
            }
            m_frame_binding_sets.push_back(binding_set);  // Keep alive until frame ends

            // Draw fullscreen quad
            auto& ctx = *m_context;
            ctx.set_pipeline(m_point_light_pipeline);
            ctx.set_binding_set(binding_set);
            ctx.set_vertex_buffer(m_fullscreen_vertex_buffer);
            ctx.set_index_buffer(m_quad_index_buffer); // Reuse quad index buffer
            ctx.draw_indexed(6);

            m_stats.draw_calls++;
        }
    }

    void renderer2d::composite_scene()
    {
        if (!m_scene_target || !m_light_accumulation)
            return;

        // Ensure composite pipeline exists
        if (!m_composite_pipeline)
        {
            pipeline_desc desc;
            desc.shader_program = m_composite_shader;
            desc.vertex_layout = m_composite_input_layout;
            desc.binding_layouts.push_back(m_composite_binding_layout);
            desc.state.blend = blend_mode::alpha;
            desc.state.depth = depth_mode::none;
            desc.state.cull = cull_mode::none;
            desc.state.primitive = topology::triangles;
            desc.color_format = m_current_color_format;
            desc.depth_format = m_current_depth_format;

            m_composite_pipeline = m_pipeline_cache->get_or_create(desc);
            if (!m_composite_pipeline)
            {
                LUMINA_LOG_ERROR("Failed to create composite pipeline");
                return;
            }
        }

        // Composite params structure (must match HLSL cbuffer layout)
        struct alignas(16) composite_params
        {
            glm::vec3 ambient_color;
            float ambient_intensity;
        };

        composite_params params;
        params.ambient_color = m_ambient_color;
        params.ambient_intensity = m_ambient_intensity;

        // Update constant buffer
        m_composite_params_buffer->update(params, m_device.get_command_list());

        // Set render target back to original (swapchain or user target)
        if (m_current_target)
        {
            m_context->set_render_target(m_current_target);
        }
        else
        {
            m_context->set_swapchain_framebuffer(m_device.get_current_framebuffer());
        }

        // Create binding set
        binding_set_desc bs_desc;
        bs_desc.layout = m_composite_binding_layout;
        bs_desc.add_constant_buffer(0, m_composite_params_buffer);
        bs_desc.add_texture(0, m_scene_target->get_color_texture());
        bs_desc.add_texture(1, m_light_accumulation->get_color_texture());
        bs_desc.add_sampler(0, m_current_sampler);

        auto binding_set = binding_set::create(m_device, bs_desc);
        if (!binding_set)
        {
            LUMINA_LOG_ERROR("Failed to create composite binding set");
            return;
        }
        m_frame_binding_sets.push_back(binding_set);  // Keep alive until frame ends

        // Draw fullscreen quad
        auto& ctx = *m_context;
        ctx.set_pipeline(m_composite_pipeline);
        ctx.set_binding_set(binding_set);
        ctx.set_vertex_buffer(m_fullscreen_vertex_buffer);
        ctx.set_index_buffer(m_quad_index_buffer);
        ctx.draw_indexed(6);

        m_stats.draw_calls++;
    }
}
